### ISSUE TITLE
更新后alist丢失

### ISSUE THREAD

**Issue by ZYong9908** [sbwml/luci-app-alist#101]
使用脚本(镜像已自行解决)从3.33.0-2更新3.33.0-3后，alist在istore管理页面中丢失，alist服务无法访问

**Comment by sbwml** [comment]
我不清楚 istore ，这个luci 安装后，他会 "网络存储"  菜单下显示

![image](https://github.com/sbwml/luci-app-alist/assets/16485166/aeb1e312-16ab-4e96-aecd-da23dbe29b4f)

**Comment by ZYong9908** [comment]
> 我不清楚 istore ，这个luci 安装后，他会 "网络存储" 菜单下显示
> 
> ![image](https://private-user-images.githubusercontent.com/16485166/318009606-aeb1e312-16ab-4e96-aecd-da23dbe29b4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDQ0ODgsIm5iZiI6MTcxMTcwNDE4OCwicGF0aCI6Ii8xNjQ4NTE2Ni8zMTgwMDk2MDYtYWViMWUzMTItMTZhYi00ZTk2LWFlY2QtZGEyM2RiZTI5YjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA5MjMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NjM2NmM5ZjBhNzA5MDVjODAzNjc1MjcyMjUwZmEzZjFlMjA2MDM1OTQ0NjY5OTFjNzBiNWU4NTE2N2U3ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.enT2KTcSrRZa4bxD2NLH8lg5o7IWFwRr_juPckX1xG0)

正常是这样的，前面多次使用脚本升级都没有问题，重新使用istore安装alist  3.29.1-2后修改数据路径和缓存路径，查看一切正常，再次尝试使用脚本升级，发现异常：
`Install Packages ...

Upgrading alist on root from 3.29.1-2 to 3.33.0-3...
Configuring alist.
Collected errors:
 * resolve_conffiles: Existing conffile /etc/alist/data.db is different from the conffile in the new package. The new conffile will be placed at /etc/alist/data.db-opkg.
 * resolve_conffiles: Existing conffile /etc/config/alist is different from the conffile in the new package. The new conffile will be placed at /etc/config/alist-opkg.
Upgrading luci-app-alist on root from 1.0.11 to 1.0.12...
Removing obsolete file /etc/config/alist.
Removing obsolete file /etc/alist/data.db.
Removing obsolete file /etc/init.d/alist.
Removing obsolete file /lib/upgrade/keep.d/luci-app-alist.
Removing obsolete file /etc/uci-defaults/luci-alist.
Not deleting modified conffile /etc/alist/data.db.
Configuring luci-app-alist.
Collected errors:
 * remove_obsolesced_files: unlinking /etc/uci-defaults/luci-alist failed: No such file or directory.
 * opkg_install_pkg: Failed to determine obsolete files from previously installed luci-app-alist
 * file_sha256sum_alloc: Failed to open file /etc/alist/data.db: No such file or directory.
Package luci-i18n-alist-zh-cn (git-23.223.34172-ff70952) installed in root is up to date.
`
同时存放路径已被修改为/mnt/xxxxxx
接下来我会尝试不修改存放路径升级

**Comment by ZYong9908** [comment]
使用istore安装3.29.1-2后，不进行任何操作，直接使用脚本升级，表现相同：在istore管理页面中丢失，alist服务无法访问
```
Install Packages ...

Upgrading alist on root from 3.29.1-2 to 3.33.0-3...
Configuring alist.
Collected errors:
 * resolve_conffiles: Existing conffile /etc/alist/data.db is different from the conffile in the new package. The new conffile will be placed at /etc/alist/data.db-opkg.
 * resolve_conffiles: Existing conffile /etc/config/alist is different from the conffile in the new package. The new conffile will be placed at /etc/config/alist-opkg.
Upgrading luci-app-alist on root from 1.0.11 to 1.0.12...
Removing obsolete file /etc/config/alist.
Removing obsolete file /etc/alist/data.db.
Removing obsolete file /etc/init.d/alist.
Removing obsolete file /lib/upgrade/keep.d/luci-app-alist.
Removing obsolete file /etc/uci-defaults/luci-alist.
Not deleting modified conffile /etc/alist/data.db.
Configuring luci-app-alist.
Collected errors:
 * remove_obsolesced_files: unlinking /etc/uci-defaults/luci-alist failed: No such file or directory.
 * opkg_install_pkg: Failed to determine obsolete files from previously installed luci-app-alist
 * file_sha256sum_alloc: Failed to open file /etc/alist/data.db: No such file or directory.
Package luci-i18n-alist-zh-cn (git-23.223.34172-ff70952) installed in root is up to date.

Done!
```
卸载以后直接使用脚本安装：alist在管理界面正常显示，但是无法启动，一直显示alist未运行，无法访问，手动启动：
```
root@iStoreOS:~# alist start
FATA[2024-03-29 09:33:44] failed to start children process: fork/exec alist: no such file or directory 

```

**Comment by sbwml** [comment]
和放哪里无关，估计是因为这个commit 的原因  https://github.com/sbwml/luci-app-alist/commit/baa383cec96dbea32527c5f0a8d650fa3951a8ba

因为有人在某群跟我说，这个alist 不适用于 openwrt snapshots （即无luci固件使用）所以原本配置文件在 luci 上的移动到 alist 包中了。


你需要尝试的操作是：备份 /etc/alist 目录。

前往openwrt 后台的软件包，搜索 alist ，把所有包含alist 名字的软件包都卸载，之后再去安装

**Comment by ZYong9908** [comment]
> rm -rf /etc/alist /etc/config/alist

确保已安装软件包无alist相关后运行`rm -rf /etc/alist /etc/config/alist`后使用脚本安装，依旧无法启动：
‘’‘
root@iStoreOS:~# alist start
FATA[2024-03-29 09:33:44] failed to start children process: fork/exec alist: no such file or directory 
’‘’

**Comment by sbwml** [comment]
这么神奇？有没有TG ，加我TG 发远程桌面我看看？

**Comment by ZYong9908** [comment]
> 这么神奇？有没有TG ，加我TG 发远程桌面我看看？

**Comment by ZYong9908** [comment]
怎么加

Bard ***@***.***>于2024年3月29日 周五17:44写道：

**Comment by sbwml** [comment]
https://t.me/sbwml

**Comment by DHDAXCW** [comment]
![image](https://github.com/sbwml/luci-app-alist/assets/74764072/813b6b19-92ef-4292-b68d-ef7b65528a1e)
一样的。。。

**Comment by sbwml** [comment]
> ![image](https://private-user-images.githubusercontent.com/74764072/318154827-813b6b19-92ef-4292-b68d-ef7b65528a1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NTgzMzQsIm5iZiI6MTcxMTc1ODAzNCwicGF0aCI6Ii83NDc2NDA3Mi8zMTgxNTQ4MjctODEzYjZiMTktOTJlZi00MjkyLWI2OGQtZWY3YjY1NTI4YTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDAwMjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MGY4NjkzNzg4OWZhMmQ0YjQ1MzhiMTZlNjhhNDgxYTJjZDk3YzczYTExMDEzNDFiYTI4NmE2MjUxNmE0MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hbmunGh3CH0Q4cjKfiNj20SkXKYi0eIpWPoeIvT8qJo) 一样的。。。

这是一个玄学问题，最后我通过 todesk 远程查看了他的路由器，检查了一遍所有的文件并没有任何错误

当我执行 `reboot`，它一切正常了。。。

**Comment by DHDAXCW** [comment]
真的吗？我重启试试

**Comment by DHDAXCW** [comment]
重启确实有效，但是关闭alist要重启才关闭，打开还是要重启。。。

**Comment by sbwml** [comment]
> 重启确实有效，但是关闭alist要重启才关闭，打开还是要重启。。。

进程不受 luci 的开关控制？

**Comment by DHDAXCW** [comment]
这个我也不清楚了，用的是lede源码

**Comment by sbwml** [comment]
> 这个我也不清楚了，用的是lede源码

有没有现成的 x86 固件测试，我用虚拟机去复现一下看看

**Comment by DHDAXCW** [comment]
我现在用的是x86物理机测试的

**Comment by ZYong9908** [comment]
我当时注意到的是在控制页面启用，偶尔会闪一下正在运行，但是最后起不来

Bard ***@***.***>于2024年3月30日 周六08:32写道：

**Comment by sbwml** [comment]
我需要一个能复现问题的固件，因为我在 OpenWrt 23.05.3 上测试不出来这样的情况

**Comment by DHDAXCW** [comment]
> > 这个我也节日了，用的是lede源码
> 
> 有没有现成的x86固件测试，我用虚拟机去复现一下看看

这是x86的固件
[固件下载](https://github.com/DHDAXCW/OpenWRT_x86_x64/releases/tag/2024.03.29-Lean3)

**Comment by sbwml** [comment]
> > > 这个我也节日了，用的是lede源码
> > 
> > 
> > 有没有现成的x86固件测试，我用虚拟机去复现一下看看
> 
> 这是x86的固件 [固件下载](https://github.com/DHDAXCW/OpenWRT_x86_x64/releases/tag/2024.03.29-Lean3)

![image](https://github.com/sbwml/luci-app-alist/assets/16485166/39b67ac6-f5bc-4ba9-9a8a-7a2072d327cf)
列表中的哪一个？

**Comment by DHDAXCW** [comment]
随便一个都可以

**Comment by sbwml** [comment]
大意了！https://github.com/sbwml/luci-app-alist/commit/dc7d9b8dc42365423d6328e7740daa3a063990d5

**Comment by DHDAXCW** [comment]
刚刷了，可以启动了~~~谢谢

**Comment by qingtian110** [comment]
> 大意了！[dc7d9b8](https://github.com/sbwml/luci-app-alist/commit/dc7d9b8dc42365423d6328e7740daa3a063990d5)

神奇的事情，明明是错的，原生 openwrt 上它依然受 ucitrack 控制的？

procd 上它的命名是  alist.init ，而 ucitrack 上声明的是 alist。但却不受影响这是什么魔法行为？

![image](https://github.com/sbwml/luci-app-alist/assets/87856890/057615e5-4def-4874-ad58-2fb85c441400)
![image](https://github.com/sbwml/luci-app-alist/assets/87856890/5c18490d-37de-4633-9f1e-ac320c862595)

**Comment by sbwml** [comment]
> > 大意了！[dc7d9b8](https://github.com/sbwml/luci-app-alist/commit/dc7d9b8dc42365423d6328e7740daa3a063990d5)
> 
> 神奇的事情，明明是错的，原生 openwrt 上它依然受 ucitrack 控制的？
> 
> procd 上它的命名是 alist.init ，而 ucitrack 上声明的是 alist。但却不受影响这是什么魔法行为？
> 

我也不清楚，我也用原生，所以他们不说我根本发现不了

**Comment by qingtian110** [comment]
> 我也不清楚，我也用原生，所以他们不说我根本发现不了

我觉得这个操作非常优雅 https://github.com/sbwml/luci-app-alist/commit/41875850a8b5f27afb0f4e61270f5a607de7f795 ，话说 mosdns 是不是也可以使用这样的的方式创建配置？

现在的 mosdns 全靠 awk、grep、sed 来生成配置文件，门槛太高了，想去魔改的人没两年 Linux 操作经验的人都望而却步

**Comment by sbwml** [comment]
> 现在的 mosdns 全靠 awk、grep、sed 来生成配置文件，门槛太高了，想去魔改的人没两年 Linux 操作经验的人都望而却步

yaml 转 json，工作量太大。以后再说
