### ISSUE TITLE
iStore系统全新安装3.33 后没有alist菜单

### ISSUE THREAD

**Issue by warcns** [sbwml/luci-app-alist#102]
大佬好，之前一直在istore上使用alist luci很正常，但是从3.32升级3.33.0-3的时候导致alist丢失，只能回退 3.32.0-2，昨天看到出了更新版好像是解决了这个问题，所以重新升级安装3.33.0-4，但是提示下面的内容：

Upgrading alist on root from 3.32.0-2 to 3.33.0-4...
Collected errors:
 * check_data_file_clashes: Package alist wants to install file /etc/init.d/alist
        But that file is already provided by package  * luci-app-alist
 * opkg_install_cmd: Cannot install package alist.
 
无奈我按照sbwml大佬的回复

> 和放哪里无关，估计是因为这个commit 的原因 https://github.com/sbwml/luci-app-alist/commit/baa383cec96dbea32527c5f0a8d650fa3951a8ba

> 因为有人在某群跟我说，这个alist 不适用于 openwrt snapshots （即无luci固件使用）所以原本配置文件在 luci 上的移动到 alist 包中了。
> 
> 你需要尝试的操作是：备份 /etc/alist 目录。
> 
> 前往openwrt 后台的软件包，搜索 alist ，把所有包含alist 名字的软件包都卸载，删除残留：
> 
> rm -rf /etc/alist /etc/config/alist
> 
> 之后再去安装

全部清理alist后重新安装提示成功，但是在网络存储菜单里依然没有alist，无奈只能全部删除，重新回退3.32.0-2才解决。

**Comment by sbwml** [comment]
一些变化的原因，它没有办法从老版本以升级的形式去更新上来。

你只能备份数据文件，然后卸载 alist 包及其依赖。之后下载最新的版本去安装然后恢复备份的数据文件（data.db）

**Comment by sbwml** [comment]
> Upgrading alist on root from 3.32.0-2 to 3.33.0-4... Collected errors:
> 
> * check_data_file_clashes: Package alist wants to install file /etc/init.d/alist
>   But that file is already provided by package  * luci-app-alist
> * opkg_install_cmd: Cannot install package alist.

这个内容表示你当前存在 3.32.0 版本。你需要继续更新，目前只能卸载旧版

**Comment by warcns** [comment]
> > Upgrading alist on root from 3.32.0-2 to 3.33.0-4... Collected errors:
> > 
> > * check_data_file_clashes: Package alist wants to install file /etc/init.d/alist
> >   But that file is already provided by package  * luci-app-alist
> > * opkg_install_cmd: Cannot install package alist.
> 
> 这个内容表示你当前存在 3.32.0 版本。你需要继续更新，目前只能卸载旧版

现在我碰到的问题是，我把旧版全部删除了，然后重新安装新版后，在网络存储菜单里依然没有alist。。。

**Comment by sbwml** [comment]
你需要 push 安装的日志上来。不然没法算命

**Comment by warcns** [comment]
> 你需要 push 安装的日志上来。不然没法算命

我先关掉alist，然后删除旧版alist，再重新安装3.33.0-4成功了，但是无法启动alist

<img width="736" alt="截屏2024-03-31 13 37 39" src="https://github.com/sbwml/luci-app-alist/assets/56870885/772b7778-0f1c-4789-96d2-610579362094">

**Comment by sbwml** [comment]
以 init.d 启动方式为准。

**Comment by warcns** [comment]
> 以 init.d 启动方式为准。

不好意思，init.d启动方式是什么意思啊？

我重新启动openwrt后依然无法启动alist，算了，我回退旧版吧。

**Comment by qzrsa** [comment]
同，以退回3.32

**Comment by jjm2473** [comment]
我在istoreos里面测试了，没有任何问题。有问题的建议检查版本号是否匹配：

```console
root@iStoreOS:~# ls -l /etc/config/alist
-rw-------    1 root     root           271 Apr 15 13:36 /etc/config/alist
root@iStoreOS:~# cat /usr/lib/opkg/info/luci-app-alist.control
Package: luci-app-alist
Version: 1.0.12
Depends: libc, alist, luci-compat
Source: /feed/luci-app-alist
SourceName: luci-app-alist
Section: luci
SourceDateEpoch: 1711544426
Maintainer: OpenWrt LuCI community
Architecture: all
Installed-Size: 3496
Description:  LuCI support for alist
root@iStoreOS:~# cat /usr/lib/opkg/info/alist.control 
Package: alist
Version: 3.33.0-4
Depends: libc, ca-bundle
Source: /feed/alist
SourceName: alist
License: GPL-3.0
Section: net
SourceDateEpoch: 1711760614
Maintainer: sbwml <admin@cooluc.com>
Architecture: x86_64
Installed-Size: 25444275
Description:  A file list program that supports multiple storage, powered by Gin and Solidjs.
```

<img width="620" alt="image" src="https://github.com/sbwml/luci-app-alist/assets/3896703/0202a0c2-bdd3-4200-849a-f77858a25380">

**Comment by jjm2473** [comment]
还有配置好以后测试能不能启动应该使用`/etc/init.d/alist start`，而不是`alist start`。

**Comment by warcns** [comment]
> 还有配置好以后测试能不能启动应该使用`/etc/init.d/alist start`，而不是`alist start`。

我的问题是删除旧版alist，重新安装3.33.0-4后，在UI界面无法启动alist，重启istoreos也不行，所以我就没再继续尝试，直接回退了。

**Comment by sbwml** [comment]
挺神奇的   我在虚拟机上装了个istoreos 来测试，我并复现不了启动不了的问题

**Comment by warcns** [comment]
> 挺神奇的 我在虚拟机上装了个istoreos 来测试，我并复现不了启动不了的问题

可能因为我的Alist是从旧版本升级上来导致的，我一直跟着你发布的更新持续更新alist版本的，得有2年了吧

**Comment by jjm2473** [comment]
升级我也测试了，从3.29升级到3.33，虽然第一次升级会失败，但是第二次就会成功。现在3.33已经发布到istore了，从istore升级就会看到两次安装过程日志（会出现两次安装过程的原因就是因为init.d和config从luci-app-alist移到alist包了，导致文件冲突）。或者卸载重装的话，那就没有任何问题，不会出现文件冲突。

**Comment by warcns** [comment]
非常感谢，解决，我的方法是：
1. 关闭alist老板本
2. 从 系统-软件包 里卸载alist所有相关项
3. 删除etc/alist 和 /etc/config/alist这两个文件夹： rm -rf /etc/alist /etc/config/alist
4. 参考https://github.com/sbwml/luci-app-alist/issues/107这个内容，删除这个文件 rm -rf /var/run/alist.sock
5. 然后从iStore直接安装Alist就正常了。

**Comment by jjm2473** [comment]
不需要删除/etc里面的文件，不然还要重新配置。

**Comment by warcns** [comment]
> 不需要删除/etc里面的文件，不然还要重新配置。

我提前备份设置了，重新安装后恢复就好了
