### ISSUE TITLE
189 Family error

### ISSUE THREAD

**Issue by lekeeith** [sbwml/luci-app-alist#11]
![image](https://user-images.githubusercontent.com/51192597/178138046-73fec9b0-7093-4846-9d1f-37108206719f.png)
应该是数值太大了，int表示不了？改成string一下看看。
这个是用你写的openwrt-alist，我还有一个部署在centos上的alist，他的189家庭云没这个问题

**Comment by sbwml** [comment]
使用上的问题你要给alist 作者反馈 ，https://github.com/alist-org/alist

这里仅仅是openwrt luci 支持，而程序源码是同步[上游](https://github.com/alist-org/alist)获取的
