### ISSUE TITLE
[requests] 增加监听配置：address

### ISSUE THREAD

**Issue by Ran-Xing** [sbwml/luci-app-alist#111]
请求增加端口监听地址配置，因为我的vps默认lan=wan也就是说，不管开不开远程访问权限，wan=lan=公网IP，所以 address 应该等于127.0.0.1

/etc/config/alist

```conf
        option address '127.0.0.1'
```

定位：

/etc/alist/config.json

```json
  "scheme": {
    "address": "127.0.0.1",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
```

/etc/init.d/alist

```diff
        if [ "$allow_wan" -eq "1" ]; then
                listen_addr="0.0.0.0"
                external_access="allow"
        else
                listen_addr=$lan_addr
                external_access="deny"
        fi

        json_add_string "address" "$listen_addr"
```

**Comment by sbwml** [comment]
这种改动可以但没有必要，因为它不符合 openwrt 正常的使用场景。

即使你把 openwrt 作为服务器系统，它也可以受 “允许从外网访问” 选项控制访问权限，因为只有启用 "允许从外网访问" 时，防火墙才会放行 alist 监听端口。此时即使你说的 lan=wan 只要防火墙端口没有开放，服务端口都不会对外暴露。

当然，如果你已经把 wan 区域入站流量已经完全放行，就当我什么都没有说过，毕竟这种行为已经没有必要考虑 alist 端口要不要对外访问了。

**Comment by Ran-Xing** [comment]
@sbwml 能给个例子吗？服务器单网卡应该是lan还是wan，防火墙是放通还是 拒绝，在哪个位置加规则呢？服务器小鸡内存太小了，尴尬

**Comment by sbwml** [comment]
对于服务器而言，应该使用 wan 接口的 DHCP 客户端，因为只有 wan 区域的防火墙可以控制服务的出入站流量。

**Comment by phantomedc** [comment]
请教：比如我使用zerotier，希望在外面访问家中的alist，zerotier是一个单独的网段，是否可以增加配置项允许alist监听这个网段？

**Comment by sbwml** [comment]
你只需要勾选允许从外网访问就行。


发自我的 Apple Watch
