### ISSUE TITLE
OpenWrt上，openclash检测不到alist的流量？

### ISSUE THREAD

**Issue by HONZYANG** [sbwml/luci-app-alist#116]
我之前一直在n1的OpenWrt上挂梯使用alist挂pikpak，最近alist更新后发现pikpak一直连不通了（电脑版没问题），于是我查看openclash的dashboard，里面居然没有pikpak的连接？是不是alist没有被openclash代理，请问应该怎么解决呢。

**Comment by HONZYANG** [comment]
wontfix😂，是我自己的操作问题吗，能否指点一下，折腾很多天了快崩溃🥲🥲，现在只能用电脑开服务看剧

**Comment by sbwml** [comment]
首先我没有接触过你说的 openclash 这个程序，所以这相关的东西我帮不了你。
其次 alist 只是一个普通的本地服务，如果你的程序能正常代理openwrt 本机流量，那么 alist 将会正常使用国外网盘。

**Comment by HONZYANG** [comment]
破案了！！！🍺。原来我用了这么多年的clash我一直不知道全局代理模式是需要在另外一个板块选择节点的，可能因为我最早用的时候瞎点已经选好了，导致后面我开全局的时候没有问题。正是因为最近折腾给重装了导致配置改变，感谢大佬指明方向我才找到了真正原因😭😭😭
