### ISSUE TITLE
openwrt-21.02-aarch64_cortex-a53.tar.gz这种为何包里只有一个文件？

### ISSUE THREAD

**Issue by woshichenghaibo** [sbwml/luci-app-alist#121]
aarch64_generic 这种包里面有三个文件才是正常的吧？

**Comment by sbwml** [comment]
所以你到底想表达些什么呢？
![QQ_1722609675288](https://github.com/user-attachments/assets/33d58862-8f28-4c9f-9ee0-819ac8faf993)

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-alist/actions/runs/10029029757/job/27716714182#step:5:6

**Comment by woshichenghaibo** [comment]
我是想说，这种只有一个文件的，而且扩展名都不是ipk的，怎么在系统里面安装呢？
________________________________
发件人: Bard ***@***.***>
发送时间: 2024年8月2日 22:43
收件人: sbwml/luci-app-alist ***@***.***>
抄送: woshichenghaibo ***@***.***>; Author ***@***.***>
主题: Re: [sbwml/luci-app-alist] openwrt-21.02-aarch64_cortex-a53.tar.gz这种为何包里只有一个文件？ (Issue #121)


https://github.com/sbwml/luci-app-alist/actions/runs/10029029757/job/27716714182#step:5:6

―

**Comment by woshichenghaibo** [comment]
你的意思是我的解压工具不对？看不到里面三个文件是吗？

**Comment by woshichenghaibo** [comment]
> 所以你到底想表达些什么呢？ ![QQ_1722609675288](https://private-user-images.githubusercontent.com/16485166/354632240-33d58862-8f28-4c9f-9ee0-819ac8faf993.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NjYxMzgsIm5iZiI6MTcyMjY2NTgzOCwicGF0aCI6Ii8xNjQ4NTE2Ni8zNTQ2MzIyNDAtMzNkNTg4NjItOGYyOC00YzlmLTllZTAtODE5YWM4ZmFmOTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA2MTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZTc0ZjZkZDZmODBkNzdiZTM5NDJmN2RkNjE5NDljOTFlYjVhMjU2MDI0MjJlMWYzMTIxNTI0ZDc1NTI0ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o_Kf07ehz7rJO4XFjMdmd4AXQP6YEF3O1W5sCHIk1zw)

我用WinRAR，确实打开只能看到一个文件，更换为7 zip之后，能看到三个文件。谢谢

**Comment by sbwml** [comment]
这很明显不是你的问题，这是我的问题。问题出在我没有使用 zip 去压缩。
