### ISSUE TITLE
immortalwrt安装软件包失败

### ISSUE THREAD

**Issue by qiang1352** [sbwml/luci-app-alist#122]
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.6.43~7cc57c32dd2ad0135ca10c30c99bfb79-r1) for kmod-fuse

**Comment by sbwml** [comment]
本仓库提供的 ipk 不依赖任何 kmod 模块。

你实际安装的，并不是来自本仓库的版本，而是 immortalwrt 官方源，建议去 immortalwrt 官方反馈
