### ISSUE TITLE
UI有个小Bug

### ISSUE THREAD

**Issue by jh0072110** [sbwml/luci-app-alist#124]
![image](https://github.com/user-attachments/assets/fad65449-f4db-49b6-9db6-ffcde365d8df)
如图所示

**Comment by sbwml** [comment]
这个 luci 目前使用 js 重写了，TypedSection CBI 控件的锅。。。

**Comment by sbwml** [comment]
fix in https://github.com/sbwml/luci-app-alist/commit/3171cc7e322aee55cd46c7a434b4d748a4e7bde0

**Comment by LIUBANGJIAN** [comment]
刚刚更新，1.1.0-1版本，openwrt的web页面不显示相关入口。

**Comment by sbwml** [comment]
现在仅兼容 LuCI2，openwrt-18.06 或更旧的 OpenWrt 无法使用。

发自我的iPhone

**Comment by LIUBANGJIAN** [comment]
> 现在仅兼容 LuCI2，openwrt-18.06 或更旧的 OpenWrt 无法使用。 发自我的iPhone
> […](#)
> 在 2024年8月14日，17:08，LIUBANGJIAN ***@***.***> 写道： ﻿ 刚刚更新，1.1.0-1版本，openwrt的web页面不显示相关入口。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

用的是L大的源，版本如下：
固件版本	OpenWrt R24.8.1 / LuCI Master (git-24.182.36151-66d29de)
内核版本	6.6.40
哪是不是用L大的版本就无法正常显示了？有其他版本吗？

**Comment by sbwml** [comment]
不支持     你可以选择安装旧版本

发自我的iPhone

**Comment by LIUBANGJIAN** [comment]
> 不支持 你可以选择安装旧版本 发自我的iPhone
> […](#)
> 在 2024年8月14日，17:31，LIUBANGJIAN ***@***.***> 写道： ﻿ 现在仅兼容 LuCI2，openwrt-18.06 或更旧的 OpenWrt 无法使用。 发自我的iPhone … 在 2024年8月14日，17:08，LIUBANGJIAN @.***> 写道： ﻿ 刚刚更新，1.1.0-1版本，openwrt的web页面不显示相关入口。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented. 用的是L大的源，版本如下： 固件版本 OpenWrt R24.8.1 / LuCI Master (git-24.182.36151-66d29de) 内核版本 6.6.40 哪是不是用L大的版本就无法正常显示了？有其他版本吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

我是用github的action来编译，通过git clone https://github.com/sbwml/luci-app-alist来拉取源，请问这种情况，怎么选择旧版本来编译呢？

**Comment by sbwml** [comment]
克隆主分支、删掉 luci-app、克隆 lua 分支

发自我的iPhone

**Comment by LIUBANGJIAN** [comment]
> 克隆主分支、删掉 luci-app、克隆 lua 分支 发自我的iPhone
> […](#)
> 在 2024年8月14日，18:05，LIUBANGJIAN ***@***.***> 写道： ﻿ 不支持 你可以选择安装旧版本 发自我的iPhone … 在 2024年8月14日，17:31，LIUBANGJIAN @.> 写道： ﻿ 现在仅兼容 LuCI2，openwrt-18.06 或更旧的 OpenWrt 无法使用。 发自我的iPhone … 在 2024年8月14日，17:08，LIUBANGJIAN @.> 写道： ﻿ 刚刚更新，1.1.0-1版本，openwrt的web页面不显示相关入口。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented. 用的是L大的源，版本如下： 固件版本 OpenWrt R24.8.1 / LuCI Master (git-24.182.36151-66d29de) 内核版本 6.6.40 哪是不是用L大的版本就无法正常显示了？有其他版本吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented. 我是用github的action来编译，通过git clone [https://github.com/sbwml/luci-app-alist来拉取源，请问这种情况，怎么选择旧版本来编译呢？](https://github.com/sbwml/luci-app-alist%E6%9D%A5%E6%8B%89%E5%8F%96%E6%BA%90%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%BF%99%E7%A7%8D%E6%83%85%E5%86%B5%EF%BC%8C%E6%80%8E%E4%B9%88%E9%80%89%E6%8B%A9%E6%97%A7%E7%89%88%E6%9C%AC%E6%9D%A5%E7%BC%96%E8%AF%91%E5%91%A2%EF%BC%9F) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

大佬不好意思，我是小白，没看明白具体是怎么操作。
