### ISSUE TITLE
Luci 菜单不显示

### ISSUE THREAD

**Issue by caixin1218** [sbwml/luci-app-alist#126]
最后一次修改后Luci 菜单就不显示alist ，之前很正常。还有一个问题是近4个月以来，mp4视频文件播放不了，以前是可以的。
（ L大源码6.1   x86_64）

**Comment by sbwml** [comment]
> 最后一次修改后Luci 菜单就不显示alist ，之前很正常

为了跟进 openwrt 上游的步伐，目前的 Luci 使用 JS 重写了。不再支持 lua 环境的 openwrt 使用，就像你说的 lede，如果你的固件使用 https://github.com/coolsnowwolf/lede/blob/b7c03c0fc986fa764244eff23b73d5caba6f2e60/feeds.conf.default#L3 openwrt-23.05 的 luci 源码进行编译则可以使用这里的最新 luci 源码。

即使你当前依然再使用较老的 luci，你也可以通过 最新 alist.ipk 包 + 以往发布的 [v3.35.0](https://github.com/sbwml/luci-app-alist/releases/tag/v3.35.0) 的 luci-app-alist.ipk 这样的方式去使用。因为正常来讲，luci 是不需要更新的，只需要更新 alist 包。

> 还有一个问题是近4个月以来，mp4视频文件播放不了，以前是可以的。

这个问题你需要前往 alist 官方仓库去反馈，因为这是 [alist](https://github.com/alist-org/alist) 提供支持的内容。

**Comment by caixin1218** [comment]
收到您的回复我很感谢，这让我明白问题所在。
那再次请教，我执行的是这种方式sed -i '$a src-git Alist  https://github.com/sbwml/luci-app-alist.git'       feeds.conf.default
那如何将版本固定在v3.35.0 呢？
我cd到 feeds/luci/applications/luci-app-alist 目录下,执行 git tag 却没有版本选择 , git branch 显示也只有master 
这让我不知道如何操作，感谢详解。

**Comment by sbwml** [comment]
你说的这些东西已经脱离这个仓库需要解决的问题。如果你实在不知道怎么弄，可以参考：

https://github.com/sbwml/luci-app-alist/commit/d0111602ec4cf6ecadbbb116659e4f99259f137d#commitcomment-145503256

**Comment by fyngd** [comment]
> 你说的这些东西已经脱离这个仓库需要解决的问题。如果你实在不知道怎么弄，可以参考：
> 
> [d011160#commitcomment-145503256](https://github.com/sbwml/luci-app-alist/commit/d0111602ec4cf6ecadbbb116659e4f99259f137d#commitcomment-145503256)

大佬，皆因很多人都用 18.06 luci-theme-argon 主题，请酌情保留一个旧版可匹配的 alist 用来编译。

**Comment by sbwml** [comment]
lua 分支就可用于 18.06

发自我的iPhone

**Comment by caixin1218** [comment]
> 你说的这些东西已经脱离这个仓库需要解决的问题。如果你实在不知道怎么弄，可以参考：
> 
> [d011160#commitcomment-145503256](https://github.com/sbwml/luci-app-alist/commit/d0111602ec4cf6ecadbbb116659e4f99259f137d#commitcomment-145503256)

已经解决了
$ git clone https://github.com/sbwml/luci-app-alist     feeds/luci/applications/luci-app-alist
lede/feeds/luci/applications/luci-app-alist$git tag 
lede/feeds/luci/applications/luci-app-alist$git checkout v3.35.0

这样就可以了，v3.36.0以后的版本luci菜单就不显示了。

**Comment by eearphon** [comment]
> > 最后一次修改后Luci 菜单就不显示alist ，之前很正常
> 
> 为了跟进 openwrt 上游的步伐，目前的 Luci 使用 JS 重写了。不再支持 lua 环境的 openwrt 使用，就像你说的 lede，如果你的固件使用 https://github.com/coolsnowwolf/lede/blob/b7c03c0fc986fa764244eff23b73d5caba6f2e60/feeds.conf.default#L3 openwrt-23.05 的 luci 源码进行编译则可以使用这里的最新 luci 源码。
> 
> 即使你当前依然再使用较老的 luci，你也可以通过 最新 alist.ipk 包 + 以往发布的 [v3.35.0](https://github.com/sbwml/luci-app-alist/releases/tag/v3.35.0) 的 luci-app-alist.ipk 这样的方式去使用。因为正常来讲，luci 是不需要更新的，只需要更新 alist 包。
> 
> > 还有一个问题是近4个月以来，mp4视频文件播放不了，以前是可以的。
> 
> 这个问题你需要前往 alist 官方仓库去反馈，因为这是 [alist](https://github.com/alist-org/alist) 提供支持的内容。



> > 最后一次修改后Luci 菜单就不显示alist ，之前很正常
> 
> 为了跟进 openwrt 上游的步伐，目前的 Luci 使用 JS 重写了。不再支持 lua 环境的 openwrt 使用，就像你说的 lede，如果你的固件使用 https://github.com/coolsnowwolf/lede/blob/b7c03c0fc986fa764244eff23b73d5caba6f2e60/feeds.conf.default#L3 openwrt-23.05 的 luci 源码进行编译则可以使用这里的最新 luci 源码。
> 
> 即使你当前依然再使用较老的 luci，你也可以通过 最新 alist.ipk 包 + 以往发布的 [v3.35.0](https://github.com/sbwml/luci-app-alist/releases/tag/v3.35.0) 的 luci-app-alist.ipk 这样的方式去使用。因为正常来讲，luci 是不需要更新的，只需要更新 alist 包。
> 
> > 还有一个问题是近4个月以来，mp4视频文件播放不了，以前是可以的。
> 
> 这个问题你需要前往 alist 官方仓库去反馈，因为这是 [alist](https://github.com/alist-org/alist) 提供支持的内容。

建议是不是为 luci18 搞个分支？毕竟使用lede的不在少数，直接clone使用方便新手

**Comment by cjlhll** [comment]
> git clone https://github.com/sbwml/luci-app-alist feeds/luci/applications/luci-app-alist
> lede/feeds/luci/applications/luci-app-alist$git tag
> lede/feeds/luci/applications/luci-app-alist$git checkout v3.35.0

lua分支缺少alist依赖呢。编译报错了。能把最新alist依赖同步到lua分支么。

**Comment by caixin1218** [comment]
> > git clone https://github.com/sbwml/luci-app-alist feeds/luci/applications/luci-app-alist
> > lede/feeds/luci/applications/luci-app-alist$git tag
> > lede/feeds/luci/applications/luci-app-alist$git checkout v3.35.0
> 
> lua分支缺少alist依赖呢。编译报错了。能把最新alist依赖同步到lua分支么。

缺依赖是你的环境有问题

**Comment by 77160860** [comment]
原来是要用1013的luci才能显示出来   ！！！
