### ISSUE TITLE
使用Imp Wrt，修改配置文件重启后，始终无法正确调用

### ISSUE THREAD

**Issue by rk26037** [sbwml/luci-app-alist#127]
根据官方文档，修改了首行Froce为False了，还是调用了系统的配置文件。这个可以解决吗？

**Comment by sbwml** [comment]
目前通过 luci 启动的 alist 无法进行手动修改配置文件，只能通过命令行进行启动。

**Comment by sbwml** [comment]
b8b5ba4367403893eac0cf248e7b0f4c9bdd51a5  下个版本起（luci-app-alist 1.1.1），将会支持完全定义 alist 配置文件
