### ISSUE TITLE
日志路径修改无效

### ISSUE THREAD

**Issue by ZYong9908** [sbwml/luci-app-alist#130]
最新`3.37.3(x86_64)` 界面配置如下：
![image](https://github.com/user-attachments/assets/e13fa464-5182-42fb-a7f7-c0a9a1b6f478)
手动修改config.json中的 `log.name：/mnt/sata2-1/log/alist/alist.log`后启动alist，发现该设置自行恢复默认`/var/log/alist.log`

**Comment by sbwml** [comment]
预期行为

发自我的iPhone

**Comment by ZYong9908** [comment]
> 预期行为 发自我的iPhone
> […](#)
> 在 2024年9月18日，11:22，ZYong ***@***.***> 写道： ﻿ 最新3.37.3(x86_64) 界面配置如下： image.png (view on web) 手动修改config.json中的 log.name：/mnt/sata2-1/log/alist/alist.log后启动alist，发现该设置自行恢复默认/var/log/alist.log — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

请问如何正确修改日志位置，这对我来说是必须项

**Comment by sbwml** [comment]
不使用 luci-app-alist 即可，使用传统命令行方式启动 alist，可以完全自主设置配置文件。

发自我的iPhone

**Comment by ZYong9908** [comment]
感谢，已解决

Bard ***@***.***>于2024年9月18日 周三11:28写道：
