### ISSUE TITLE
Alist 未运行，但实际已经运行，通过网页能进去

### ISSUE THREAD

**Issue by xuexijiaoben** [sbwml/luci-app-alist#134]
是用immortalwrt master 分支编译的系统，
弄了几次都是显示Alist 未运行，但是通过IP：5244能进去，
求解

**Comment by sbwml** [comment]
imm 和 openwrt 官方的 master 分支的源码已经自带 alist，所以你编译的时候是编译了官方源的，而不是这里的。你编译的时候也没有必要从这里拉源码了

**Comment by xuexijiaoben** [comment]
> imm 和 openwrt 官方的 master 分支的源码已经自带 alist，所以你编译的时候是编译了官方源的，而不是这里的。你编译的时候也没有必要从这里拉源码了

官方的我编译的时候删了，再拉的这个，官方的我试了下界面比较简陋，所以用了你这个，
大神有时间可以看看，没时间也没关系，现在也能用，

**Comment by sbwml** [comment]
如果你编译的时候 alist 和 luci-app-alist 都从 feeds 中删除然后使用这里的，那么它肯定能正常使用，因为我自己就在用 openwrt master。

但是如果你固件出现过一次来自 openwrt 官方feeds 的 alist，那么就没法使用这里的版本了，因为配置文件不通用。会导致读取配置失败。

**Comment by xuexijiaoben** [comment]
> 如果你编译的时候 alist 和 luci-app-alist 都从 feeds 中删除然后使用这里的，那么它肯定能正常使用，因为我自己就在用 openwrt master。
> 
> 但是如果你固件出现过一次来自 openwrt 官方feeds 的 alist，那么就没法使用这里的版本了，因为配置文件不通用。会导致读取配置失败。

感谢，这样解决了，请关闭吧，
