### ISSUE TITLE
OpenWrt 21.02.3 在 luci 顶部找不到 alist

### ISSUE THREAD

**Issue by peeweep** [sbwml/luci-app-alist#15]
在顶部没有nas，通过地址是可以直接访问的，所以是不是移到 services  里会好一些？

![image](https://user-images.githubusercontent.com/624223/181995081-91b4c76a-8872-4b48-b58b-e9e4fa552db9.png)

**Comment by sbwml** [comment]
放在NAS 菜单是刻意为之。因为其实不止有这一个开源插件被放在这个菜单里。而OpenWRT 的菜单它是根据已安装的插件自动新增类别的，你图中没有这个菜单可能是openwrt luci 缓存，可能是浏览器缓存。

![](https://user-images.githubusercontent.com/16485166/182002922-e82014af-cabb-458f-906d-0a8a124b424e.png)

**Comment by peeweep** [comment]
我清理了 luci 缓存和浏览器缓存还是看不到 NAS 菜单，请问还有其他地方要清理吗？

```
rm -rf /tmp/luci-*
uci set luci.ccache.enable=0; uci commit luci
```

**Comment by sbwml** [comment]
> 我清理了 luci 缓存和浏览器缓存还是看不到 NAS 菜单，请问还有其他地方要清理吗？
> 
> ```
> rm -rf /tmp/luci-*
> uci set luci.ccache.enable=0; uci commit luci
> ```

我大概了解你的情况了   一会给它做个workaround吧
