### ISSUE TITLE
lienol openwrt 22.03编译报错找不到fuse.h

### ISSUE THREAD

**Issue by avsba001** [sbwml/luci-app-alist#18]
安装过libfuse，已按wiki执行过拉取
`
make[3]: Entering directory '/home/avsba001/openwrt/package/alist/alist'
rm -f /home/avsba001/openwrt/build_dir/target-mipsel_24kc_musl/alist-3.0.0-rc.0/.built
touch /home/avsba001/openwrt/build_dir/target-mipsel_24kc_musl/alist-3.0.0-rc.0/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/avsba001/openwrt/tmp/go-build" GO_MOD_CACHE_DIR="/home/avsba001/openwrt/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/alist-org/alist" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/alist-org/alist/..." GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/avsba001/openwrt/build_dir/target-mipsel_24kc_musl/alist-3.0.0-rc.0" GO_BUILD_DIR="/home/avsba001/openwrt/build_dir/target-mipsel_24kc_musl/alist-3.0.0-rc.0/.go_work/build" GO_BUILD_BIN_DIR="/home/avsba001/openwrt/build_dir/target-mipsel_24kc_musl/alist-3.0.0-rc.0/.go_work/build/bin/linux_mipsle" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/avsba001/openwrt/staging_dir/target-mipsel_24kc_musl/usr/share/gocode/src" GOOS="linux" GOARCH="mipsle" GO386="" GOAMD64="" GOARM="" GOMIPS="softfloat" GOMIPS64="" GOPPC64="" CGO_ENABLED=1 CC="mipsel-openwrt-linux-musl-gcc" CXX="mipsel-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -mno-branch-likely -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -fmacro-prefix-map=/home/avsba001/openwrt/build_dir/target-mipsel_24kc_musl/alist-3.0.0-rc.0=alist-3.0.0-rc.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/home/avsba001/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/usr/include -I/home/avsba001/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/include/fortify -I/home/avsba001/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/include" CGO_CXXFLAGS="-Os -pipe -mno-branch-likely -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -fmacro-prefix-map=/home/avsba001/openwrt/build_dir/target-mipsel_24kc_musl/alist-3.0.0-rc.0=alist-3.0.0-rc.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/home/avsba001/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/usr/lib -L/home/avsba001/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib -znow -zrelro" GOPATH="/home/avsba001/openwrt/build_dir/target-mipsel_24kc_musl/alist-3.0.0-rc.0/.go_work/build" GOCACHE="/home/avsba001/openwrt/tmp/go-build" GOMODCACHE="/home/avsba001/openwrt/dl/go-mod-cache" GOENV=off /usr/bin/env bash /home/avsba001/openwrt/feeds/packages/lang/golang//golang-build.sh build -v -buildvcs=false -trimpath -ldflags "all=-buildid '1661521482' -linkmode external -extldflags '-L/home/avsba001/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/usr/lib -L/home/avsba001/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"     -installsuffix "softfloat"   -ldflags "-w -s -X github.com/alist-org/alist/v3/internal/conf.Version=v3.0.0-rc.0-mipsel -X github.com/alist-org/alist/v3/internal/conf.WebVersion=3.0.0-rc.0 -buildid '1661521482' -linkmode external -extldflags '-L/home/avsba001/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/usr/lib -L/home/avsba001/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"  
Finding targets

Building targets
github.com/winfsp/cgofuse/fuse
# github.com/winfsp/cgofuse/fuse
../../../../../dl/go-mod-cache/github.com/winfsp/cgofuse@v1.5.0/fuse/host_cgo.go:116:10: fatal error: fuse.h: No such file or directory
 #include <fuse.h>
          ^~~~~~~~
compilation terminated.

make[3]: *** [Makefile:91: /home/avsba001/openwrt/build_dir/target-mipsel_24kc_musl/alist-3.0.0-rc.0/.built] Error 2
make[3]: Leaving directory '/home/avsba001/openwrt/package/alist/alist'
time: package/alist/alist/compile#1.99#0.59#1.99
    ERROR: package/alist/alist failed to build.
make[2]: *** [package/Makefile:116: package/alist/alist/compile] Error 1
make[2]: Leaving directory '/home/avsba001/openwrt'
make[1]: *** [package/Makefile:110: /home/avsba001/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/avsba001/openwrt'
make: *** [/home/avsba001/openwrt/include/toplevel.mk:230: world] Error 2
`

**Comment by sbwml** [comment]
给编译环境安装 fuse 开发包

ubuntu/debian:
```shell
sudo apt update
sudo apt install libfuse-dev
```

redhat:
```shell
sudo yum install fuse-devel
```

**Comment by avsba001** [comment]
谢谢，解决了

**Comment by sclsyin** [comment]
请问一下云编译怎么添加呢？

**Comment by sbwml** [comment]
> 请问一下云编译怎么添加呢？

GitHub Actions 在执行编译操作前，你任何可执行命令的shell脚本或工作流都可以安装它。

比如 https://github.com/sbwml/builder/commit/4daa69d2c2868518a80d1e185dcd9f1e5a24dc6c
