### ISSUE TITLE
lean源码×86内核8.19编译报错

### ISSUE THREAD

**Issue by firkerword** [sbwml/luci-app-alist#19]
![S20916-19262183](https://user-images.githubusercontent.com/61251923/190629075-1d0cef3b-b12b-4460-951b-c03dfb3de37b.png)
[错误日志](https://github.com/firkerword/openwrt-Exclusive/actions/runs/3064879645/jobs/4948424672)

**Comment by firkerword** [comment]
已有答案

**Comment by xuanranran** [comment]
我的也是lean，編譯错误，解决办法是什么呢？
![IMG_20220917_185826_346](https://user-images.githubusercontent.com/20316324/190853300-5b6a7a1b-d72a-4eb9-8ab1-7f49f08019a3.jpg)

**Comment by sbwml** [comment]
> 我的也是lean，編譯错误，解决办法是什么呢？ ![IMG_20220917_185826_346](https://user-images.githubusercontent.com/20316324/190853300-5b6a7a1b-d72a-4eb9-8ab1-7f49f08019a3.jpg)

#18
