### ISSUE TITLE
3.0.0rc，web页面没有新建文件夹、上传等功能

### ISSUE THREAD

**Issue by tianiue** [sbwml/luci-app-alist#20]
web页面一直显示加载
![11122](https://user-images.githubusercontent.com/61725402/190944164-2f82e2a8-f84a-4545-8363-266b6fad70b3.png)

**Comment by sbwml** [comment]
https://alist.nn.ci/zh/

**Comment by sbwml** [comment]
ps: 2.x 依旧可用  https://github.com/sbwml/luci-app-alist/releases/tag/v2.6.4
