### ISSUE TITLE
lean源编译失败

### ISSUE THREAD

**Issue by tianiue** [sbwml/luci-app-alist#21]
make[3]: Entering directory '/workdir/openwrt/package/luci-app-alist/alist'
SHELL= flock /workdir/openwrt/tmp/.root-copy.flock -c 'cp -fpR /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/r8168-8.050.03/.pkgdir/kmod-r8168/. /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/'
touch /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp/.kmod-r8168_installed
echo "kmod-r8168" >> /workdir/openwrt/staging_dir/target-x86_64_musl/pkginfo/r8168.default.install
make[3]: Leaving directory '/workdir/openwrt/package/lean/r8168'
time: package/lean/r8168/compile#0.24#0.07#0.33
make[3]: Entering directory '/workdir/openwrt/feeds/packages/libs/expat'
mkdir -p /workdir/openwrt/dl
SHELL= flock /workdir/openwrt/tmp/.alist-3.0.0-rc.1.tar.gz.flock -c '  	/workdir/openwrt/scripts/download.pl "/workdir/openwrt/dl" "alist-3.0.0-rc.1.tar.gz" "f0a403e1ef98f2721648cabc60a2912d6776906e9703042bdaebe6284c77b1a9" "" "https://codeload.github.com/alist-org/alist/tar.gz/v3.0.0-rc.1?"    '
rm -f /workdir/openwrt/build_dir/target-x86_64_musl/alist-3.0.0-rc.1/.built
touch /workdir/openwrt/build_dir/target-x86_64_musl/alist-3.0.0-rc.1/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/workdir/openwrt/tmp/go-build" GO_MOD_CACHE_DIR="/workdir/openwrt/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/alist-org/alist" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/alist-org/alist/..." GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/workdir/openwrt/build_dir/target-x86_64_musl/alist-3.0.0-rc.1" GO_BUILD_DIR="/workdir/openwrt/build_dir/target-x86_64_musl/alist-3.0.0-rc.1/.go_work/build" GO_BUILD_BIN_DIR="/workdir/openwrt/build_dir/target-x86_64_musl/alist-3.0.0-rc.1/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/workdir/openwrt/staging_dir/target-x86_64_musl/usr/share/gocode/src" GOOS="linux" GOARCH="amd64" GO386="" GOAMD64="v1" GOARM="" GOMIPS="" GOMIPS64="" GOPPC64="" CGO_ENABLED=1 CC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/workdir/openwrt/build_dir/target-x86_64_musl/alist-3.0.0-rc.1=alist-3.0.0-rc.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include" CGO_CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/workdir/openwrt/build_dir/target-x86_64_musl/alist-3.0.0-rc.1=alist-3.0.0-rc.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro" GOPATH="/workdir/openwrt/build_dir/target-x86_64_musl/alist-3.0.0-rc.1/.go_work/build" GOCACHE="/workdir/openwrt/tmp/go-build" GOMODCACHE="/workdir/openwrt/dl/go-mod-cache" GOENV=off /usr/bin/env bash /workdir/openwrt/feeds/packages/lang/golang//golang-build.sh build -v -buildvcs=false -trimpath -ldflags "all=-buildid '1663508545' -linkmode external -extldflags '-L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'"        -ldflags "-w -s -X github.com/alist-org/alist/v3/internal/conf.Version=v3.0.0-rc.1-x86_64 -X github.com/alist-org/alist/v3/internal/conf.WebVersion=3.0.0-rc.1 -buildid '1663508545' -linkmode external -extldflags '-L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'"  
Finding targets

**Comment by sbwml** [comment]
参考其它issues
