### ISSUE TITLE
最新的云编译会出错

### ISSUE THREAD

**Issue by aiastia** [sbwml/luci-app-alist#26]
make[3]: *** [Makefile:102: /workdir/openwrt/build_dir/target-x86_64_musl/alist-3.0.3/.built] Error 2
make[3]: Leaving directory '/workdir/openwrt/feeds/alist_luci/alist'
time: package/feeds/alist_luci/alist/compile#3.19#0.96#2.82
    ERROR: package/feeds/alist_luci/alist failed to build.
make[2]: *** [package/Makefile:116: package/feeds/alist_luci/alist/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by sbwml** [comment]
虽然不清楚为什么你不提供任何日志，但是我猜测与该issues 类同 #18
