### ISSUE TITLE
加载大图片时导致路由器崩溃，无响应

### ISSUE THREAD

**Issue by Sailiy** [sbwml/luci-app-alist#27]
你好，非常感谢你为alist的付出
我在竞斗云的路由器山安装了这个包，并且使用了路由器上的内存卡插槽插内存卡当作本地存储。
我在里边放的mp4视频文件可以正常播放。
但是我放的jpg图片（原始照片，一张照片大概3-5MB），在线浏览和下载时，会导致路由器崩溃，无响应；希望能解决这个问题

**Comment by sbwml** [comment]
通过挂载sd卡访问 124M 图片依旧无法复现所说问题
![11](https://user-images.githubusercontent.com/16485166/194891529-25dadc01-62c7-4678-95b5-d5bfd9f68847.png)
![22](https://user-images.githubusercontent.com/16485166/194891538-453e98b2-5148-4c04-bf6f-88e0ce59d773.png)

**Comment by saplf** [comment]
我这边在路由器上也出现了，看日志是 oom 内存不够，应该是 alist 自带的 web 服务没针对低内存设备做特殊处理，webdav 服务就没这个问题，所以我直接不用他的页面了，要他页面功能的时候在客户端再启动一个 alist 服务连接路由器的 /dav，一样可以用
