### ISSUE TITLE
云编译错误

### ISSUE THREAD

**Issue by Tuz10** [sbwml/luci-app-alist#28]
make[3]: *** [Makefile:102: /workdir/openwrt/build_dir/target-mipsel_24kc_musl/alist-3.1.0/.built] Error 2
make[3]: Leaving directory '/workdir/openwrt/feeds/NueXini_Packages/alist'
time: package/feeds/NueXini_Packages/alist/compile#3.02#0.91#2.69
    ERROR: package/feeds/NueXini_Packages/alist failed to build.
make[2]: *** [package/Makefile:116: package/feeds/NueXini_Packages/alist/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2

**Comment by sbwml** [comment]
置顶issue 能帮到你就帮到你，不难帮到你我也没办法

**Comment by Tuz10** [comment]
谢谢大佬，云编译的话具体是在哪里加sudo apt update
sudo apt install libfuse-dev 
回复看不懂

**Comment by Tuz10** [comment]
实体的会，有梯，但是还是会出问题，老是折腾，云编译不知道这行代码放哪个文件哪里行，可以问问嘛，不好意思，麻烦大佬了

**Comment by sbwml** [comment]
仅供参考  https://github.com/sbwml/builder/blob/master/.github/workflows/build-release.yml#L63

GitHub Runner 五花八门，没有统一的哪一个文件，哪一行

**Comment by Tuz10** [comment]
谢谢大佬，已经可以了
