### ISSUE TITLE
3.2 云编译构建失败

### ISSUE THREAD

**Issue by rq1025330** [sbwml/luci-app-alist#29]
![image](https://user-images.githubusercontent.com/52870887/196044293-8cea7547-131f-46cc-9f6d-b4a2cfe3fc85.png)
大佬 必须使用ni你提供的rm -rf feeds/packages/lang/golang
svn export https://github.com/sbwml/packages_lang_golang/branches/19.x feeds/packages/lang/golang才行？

**Comment by sbwml** [comment]
可能  大概吧

**Comment by rq1025330** [comment]
我看了  现在openwrt是18.4 的缘故 你现在是19.X

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-alist#how-to-build
