### ISSUE TITLE
可否为glibc 版本太低的用户编译一个版本的IPK？

### ISSUE THREAD

**Issue by master-yun-yun** [sbwml/luci-app-alist#31]
你好！
我的路由器是LINKSYS WRT1900ACS
下载你的IPK任何一个版本均无法运行
根据  https://alist.nn.ci/zh/guide/install/manual.html#%E8%8E%B7%E5%8F%96-alist  [的说明](https://alist.nn.ci/zh/guide/install/manual.html#%E8%8E%B7%E5%8F%96-alist)
**

- > 如果你的 glibc 版本太低，建议下载 musl 版本
- > 下载musl版本确实可以运行，而其他版本无法运行

**
但是该版本需要占用USB口及USB设备，不太方便。
可否为glibc 版本太低的用户编译一个版本的IPK？

**Comment by sbwml** [comment]
我没法针对某个soc 某个openwrt 衍生版编译     目前提供的版本对标官方openwrt 21.02 分支
