### ISSUE TITLE
升级了alist 导致 luci-app-alist 无法启动和读取密码

### ISSUE THREAD

**Issue by zhoujinshi** [sbwml/luci-app-alist#34]
alist: 被你升级了 v3.6.0
luci-app-alist 控制命令变更了 是不是需要调整下
alist start 启动
alist admin 查看密码 可以获取最后两行

**Comment by sbwml** [comment]
这样的吗   我也不太清楚    这个是服务器自己升级的    晚点我试试

**Comment by sbwml** [comment]
有打听到结果，luci是没问题的，你需要更新一下alist luci ipk了，可能因为版本号没变，无法直接升级luci，你可以卸载掉重新下载luci ipk安装就能正常了

**Comment by zhoujinshi** [comment]
http://lede.hta.ink/ 我这里安装了一个 PC X86 虚拟机 的没有密码的

ROM下载地址 https://wetransfer.com/downloads/8c50e22e6014ba6791bf6dc33de115bb20221216080422/be31ca/grid

**Comment by zhoujinshi** [comment]
env: can't execute '/etc/init.d/alist': Permission denied
我知道原因了 是这个没有权限
