### ISSUE TITLE
GL-SF1200 路由器 mips_siflower 

### ISSUE THREAD

**Issue by mrsmileyuen** [sbwml/luci-app-alist#38]
大佬能支持GL-SF1200 路由器吗 多谢了 
我查到的架构信息如下  
arch all 1
arch noarch 1
arch mips_siflower 10  
我查阅了下面的文章 
https://blog.csdn.net/u011570312/article/details/120546354
https://github.com/gl-inet/openwrt/tree/openwrt-18.06-siflower

**Comment by sbwml** [comment]
> https://github.com/gl-inet/openwrt/tree/openwrt-18.06-siflower

你发的这些连接根本就不是什么sdk，连toolchain都不带。ipk 我只能提供官方 openwrt sdk 支持的架构

**Comment by sbwml** [comment]
这里只是alist 路由安装的一种方式 之一。如果没有适用自己的架构 ，你应该去alist 作者仓库下载二进制文件来运行

**Comment by shu0802** [comment]
启用ssl证书提示错误
![1672150644151](https://user-images.githubusercontent.com/43750373/209679369-cbb2c46b-e7a6-4bd9-8dd5-054c460e6104.png)

**Comment by sbwml** [comment]
你需要明白ssl 是什么
