### ISSUE TITLE
hash不对

### ISSUE THREAD

**Issue by oyksoft** [sbwml/luci-app-alist#39]
最新更新：
https://github.com/sbwml/luci-app-alist/commit/f42d623fc50b30f38c040f4eae54291e175e3fb1
最新是3.9.2，hash值：0e102eea65f6d3b0d247c6c73c97a3ae7d04c71ba9962d3897e04dca8877cf3e是正确的，为什么又更新一个错误的hash值呢？错误值：32ab34659f0c582fb782b331df6ab7405a4a2c8a9c1dff0825ad6e163ef1a148。
导致编译通不过。望立即修正。谢谢。

**Comment by sbwml** [comment]
revert 掉了    昨晚github傻逼了
