### ISSUE TITLE
luci-app-alist编译报错

### ISSUE THREAD

**Issue by XIAOZHAOXSXH** [sbwml/luci-app-alist#40]
Building targets
github.com/winfsp/cgofuse/fuse
# github.com/winfsp/cgofuse/fuse
../../../../../dl/go-mod-cache/github.com/winfsp/cgofuse@v1.5.0/fuse/host_cgo.go:117:10: fatal error: fuse.h: No such file or directory
 #include <fuse.h>
          ^~~~~~~~
compilation terminated.

抱歉占用一个issue，这两天在编译alist的时候一直报这个错误，无法继续编译，更换golang版本也不行，看了一下正确地址应该是github.com/winfsp/cgofuse/tree/master/fuse，有大佬知道怎么修改吗？

**Comment by sbwml** [comment]
看置顶问题

**Comment by XIAOZHAOXSXH** [comment]
已经解决了感谢
