### ISSUE TITLE
3.11.0修复了阿里云invalid X-Device-Id求更新

### ISSUE THREAD

**Issue by m0eak** [sbwml/luci-app-alist#41]

**Comment by winner890302** [comment]
同求

**Comment by Singmin** [comment]
同求

**Comment by bboysingle** [comment]
更新到3.11.0版本后，自己的阿里云盘还是不能播放视频，显示 failed get link: Device offline  不清楚什么原因啊，希望大佬帮看下

**Comment by bboysingle** [comment]
> 更新到3.11.0版本后，自己的阿里云盘还是不能播放视频，显示 failed get link: Device offline 不清楚什么原因啊，希望大佬帮看下

原来是需要移动端的token，更新后可以观看了
