### ISSUE TITLE
版本不对呢？是不是哪操作错了？

### ISSUE THREAD

**Issue by hyy34** [sbwml/luci-app-alist#44]
下载的[alist_3.11.0-1_arm_cortex-a7.ipk](https://github.com/sbwml/luci-app-alist/releases/download/v3.11.0/alist_3.11.0-1_arm_cortex-a7.ipk)

离线安装，后台显示是v2.6.4-arm版本。

**Comment by sbwml** [comment]
终端运行这个脚本

sh -c "$(curl -ksS https://raw.githubusercontent.com/sbwml/luci-app-alist/master/install.sh)"

把终端输出的内容复制贴出来看看

**Comment by hyy34** [comment]
> sh -c "$(curl -ksS https://raw.githubusercontent.com/sbwml/luci-app-alist/master/install.sh)"

又试了下，离线又安装不了。。运行脚本方式，提示
Checking available space  ...

Error, The system storage space is less than 40MB.

**Comment by sbwml** [comment]
你机器没空间了   装不下

**Comment by hyy34** [comment]
> 你机器没空间了 装不下

我是竞斗云2.0，软件包现在使用45%还剩下22MB，的确不够。。但是我咋记得竞斗云是128MB的。。

**Comment by sbwml** [comment]
这我就不清楚你那个机器了   反正装或者更新   你至少需要40M + 的可用空间    你可以先卸载旧版本   再重试装新版本

**Comment by sbwml** [comment]
当然了   如果你自己有linux   你可以用sdk 去编译一个带upx 压缩的版本   可以降低空间占用
