### ISSUE TITLE
前几天还好好的，现在编译又报错。

### ISSUE THREAD

**Issue by woni928** [sbwml/luci-app-alist#46]
<img width="624" alt="2023-02-18_224624" src="https://user-images.githubusercontent.com/28220733/219872485-c7adbcfb-33cf-4d85-b5f9-bcb9dfe23e8b.png">
V 3.11之前没有问题，依赖已经安装的前提下还是出错，请求帮助。

**Comment by sbwml** [comment]
刚刚测试了，编译没问题。如果有问题，我这个仓库runner 也无法编译出ipk文件。

检查你拉取的源码是不是通过 https://github.com/sbwml/luci-app-alist 这个仓库，而不是来自任何的插件合集仓库收录
