### ISSUE TITLE
要自己编译吗，下载编译好的不能安装

### ISSUE THREAD

**Issue by michealhansun** [sbwml/luci-app-alist#50]
opkg install alist_3.12.2-1_x86_64.ipk luci-app-alist_1.0.8_all.ipk luci-i18n-alist-zh-cn_git-23.052.44271-9d6f8d3_all.ipk 
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Package alist (3.12.2-1) installed in root is up to date.
Package luci-app-alist (1.0.8) installed in root is up to date.
Package luci-i18n-alist-zh-cn (git-23.052.44271-9d6f8d3) installed in root is up to date.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.94-1-d282af7706ae22b64a072a63c482db12) for kmod-crypto-hash
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.94-1-d282af7706ae22b64a072a63c482db12) for kmod-crypto-null
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.94-1-d282af7706ae22b64a072a63c482db12) for kmod-crypto-aead
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.94-1-d282af7706ae22b64a072a63c482db12) for kmod-crypto-manager
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.94-1-d282af7706ae22b64a072a63c482db12) for kmod-crypto-authenc

**Comment by sbwml** [comment]
这不是安装上了吗  alist (3.12.2-1) installed in root is up to date

**Comment by michealhansun** [comment]
哦，好的，谢谢
