### ISSUE TITLE
Assets里的luci-app-alist.ipk安装出错

### ISSUE THREAD

**Issue by zyu0090** [sbwml/luci-app-alist#51]
提示unkown package "luci-app-alist."
openwrt.org最新稳定版/releases/22.03.3/targets/x86/64/

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-alist#how-to-install-prebuilt-packages-openwrt-2122master


这里有安装步骤，如果装不上我也不懂它了。头一回接触openwrt ，知道的不比你多

**Comment by chengnan049** [comment]
不如给张截图，你是从系统内安装的吧，如果是那就正常，因为官方源不包含 Alist ，需要手动下载或者来[这里](https://supes.top)定制固件（已经更换为国内源码）

**Comment by zyu0090** [comment]
> 

我确实是走这个源下了个luci-app-alist就可以直接装了

**Comment by zyu0090** [comment]
> 不如给张截图，你是从系统内安装的吧，如果是那就正常，因为官方源不包含 Alist ，需要手动下载或者来[这里](https://supes.top)定制固件（已经更换为国内源码）

我确实是走这个源下了个luci-app-alist就可以直接装了
