### ISSUE TITLE
[New Feature Request] 延迟启动

### ISSUE THREAD

**Issue by chengnan049** [sbwml/luci-app-alist#52]
RT，DNS服务器还未完全启动，而此时 Alist 已经启动且向 DNS 服务器请求目标 IP（特别是对于 PikPak 这种限制 IP 的网盘则则还需要等待代理启动），导致无法使用存储，是否考虑增加类似 Passwall 的延迟启动功能

**Comment by sbwml** [comment]
这种事情比较尴尬，openwrt procd 自身是不支持延时启动操作的（它只有 reload delay）。你说的科学插件延时启动，是因为这类型的插件他们使用 shell 去处理启停操作，是否需要延时启动只需要在启动前 sleep 等待即可，如果把那种方法应用到这个插件，可以是可以，但是会让整体变得很奇怪，应该不会考虑。

但我可以给你一个曲线救国的方案：登入 **OpenWrt LuCI** - **系统** - **启动项** - **本地启动脚本**，在 `exit 0` 之前添加一下内容

```shell
{
  sleep 2m && /etc/init.d/alist restart
} &
```

实现开机 2 分钟后，自动重启一次 alist 服务，你可以根据实际网络情况调整等待时长。

**Comment by chengnan049** [comment]
也是一个不错的方案，刚开始也是这么想的，感谢大佬回复
