### ISSUE TITLE
R3G运行报错

### ISSUE THREAD

**Issue by GWan1234** [sbwml/luci-app-alist#55]
编译按照说明替换了golang，编译无报错，打开web运行之后一直显示：正在收集数据…
终端输入alist正常显示各种介绍，输入alist start显示：
root@OpenWrt:~# alist start
FATA[2023-03-21 04:09:55] failed to start children process: fork/exec alist: no such file or directory 
请求支援。

**Comment by sbwml** [comment]
执行文件被压缩过？

**Comment by sbwml** [comment]
直接op源码编译出来的话应该没被压缩，这种错误我也没见过，不知道什么问题
