### ISSUE TITLE
在KODI海报墙不能播放，提示掉盘

### ISSUE THREAD

**Issue by weiyouai1** [sbwml/luci-app-alist#56]
速度可以，但是用KODI没办法用，刮削以后在电影或者电视剧海报墙那里就不能播放，用群晖安装Alist或者软路由都一样，在群晖用clouddrive可以挂载为本地或者软路由安装阿里云盘WedDav都能正常使用。

**Comment by sbwml** [comment]
反馈错地方了，这里只是 openwrt 的一个小开关，alist 使用问题或疑问请前往上游反馈。
