### ISSUE TITLE
夸克在线播放限速

### ISSUE THREAD

**Issue by ASQ301** [sbwml/luci-app-alist#59]
您好 目前3.16.0版本 修复了夸克下载限速的问题  但是在线播放还是限速  alist原版已经修复了 但是还没有正式更新的版本 麻烦您关注一下 谢谢啦  https://github.com/alist-org/alist/issues/4166

**Comment by chengnan049** [comment]
luci-app-alist 只会使用发布版 AList ，Action 的不会考虑，且不要直接替换二进制文件进行升级
