### ISSUE TITLE
3.16版本夸克网盘无法正常播放

### ISSUE THREAD

**Issue by songyanbai** [sbwml/luci-app-alist#60]
![6@}TXZ A738BI7@{2ONAQ(T](https://user-images.githubusercontent.com/40381588/233826741-31d488f9-2aa9-452f-a003-593a8a86fda6.png)
![R G3BHJNLKW7K`1}1RLY4FM](https://user-images.githubusercontent.com/40381588/233826748-626760eb-923c-4a2b-86b7-fefdef4cd0b6.png)

**Comment by chengnan049** [comment]
https://github.com/alist-org/alist/issues/4166 中问题已被解决，等待稳定版发布后同步，该问题和 `luci-app-alist` 无关，请关闭此 Issues 以后有相关问题请转到 https://github.com/alist-org/alist/issues 进行反馈，
