### ISSUE TITLE
遇到这个问题怎么办

### ISSUE THREAD

**Issue by ROOOCCCK** [sbwml/luci-app-alist#63]
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.108-1-28fe4bcb31002b292bfd3ce165ac506b) for kmod-crypto-hash
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.108-1-28fe4bcb31002b292bfd3ce165ac506b) for kmod-crypto-null
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.108-1-28fe4bcb31002b292bfd3ce165ac506b) for kmod-crypto-aead
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.108-1-28fe4bcb31002b292bfd3ce165ac506b) for kmod-crypto-manager
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.108-1-28fe4bcb31002b292bfd3ce165ac506b) for kmod-crypto-user
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.108-1-28fe4bcb31002b292bfd3ce165ac506b) for kmod-crypto-authenc
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.108-1-28fe4bcb31002b292bfd3ce165ac506b) for kmod-cryptodev

**Comment by sbwml** [comment]
这个log 与alist 无关，你其它插件依赖关系导致的“警告” ，alist 不需要任何kmod 依赖，即使显示这些log ，你依然可以正常安装上alist luci

**Comment by ROOOCCCK** [comment]
> 这个log 与alist 无关，你其它插件依赖关系导致的“警告” ，alist 不需要任何kmod 依赖，即使显示这些log ，你依然可以正常安装上alist luci

直接忽略依赖安装，不会有问题的意思是吗
