### ISSUE TITLE
求助，单独编译这插件成功，但只有一个alist_3.16.3-1_aarch64_cortex-a53.ipk

### ISSUE THREAD

**Issue by freedyYang** [sbwml/luci-app-alist#65]
求助，自行本地编译成功，只有一个alist_3.16.3-1_aarch64_cortex-a53.ipk
没有 luci-app-alist_1.0.8_all.ipk 和 luci-i18n-alist-zh-cn_git-23.104.20606-8a14151_all.ipk 语言包，请问是什么问题？

**Comment by sbwml** [comment]
我不清楚，不太懂这些编译相关，openwrt 官方文档会有更多的学习资料。

但你依然可以尝试 README 的 https://github.com/sbwml/luci-app-alist#how-to-build

`make menuconfig`  # choose LUCI -> Applications -> luci-app-alist  使 CONFIG_PACKAGE_luci-app-alist=y或m   然后根据openwrt 文档去单独 make 这个luci

**Comment by freedyYang** [comment]
回复真及时 ，完整编译就 有了缺失的这2个文件，多谢~
