### ISSUE TITLE
最新版的arm_cortex-a7_neon-vfpv4版本没编译

### ISSUE THREAD

**Issue by itjso** [sbwml/luci-app-alist#66]
最新版的arm_cortex-a7_neon-vfpv4版本没编译，并且，从3.16.1版本之后的所有版本你编译的a7_neon-vfpv4都无法运行，我是回退到3.16.0用了一个月的，终于等到3.17.0竟然直接没了a7_neon-vfpv4版本，a7_neon-vfpv4版本还是有必要的。希望编译感谢。

**Comment by sbwml** [comment]
你在路由器执行   `ldd --version` 截图我看看

**Comment by itjso** [comment]
用了你刚才更新的openwrt-21.02-arm_cortex-a7_neon-vfpv4.tar可以了，应该是之前从3.16.1开始你没使用21.02的原因。辛苦了，感谢！
