### ISSUE TITLE
master分支编译报错，看openwrt/packages的issues反馈应该是musl 1.2.4依赖的问题

### ISSUE THREAD

**Issue by wzming** [sbwml/luci-app-alist#67]
报错如下图：
![image](https://github.com/sbwml/luci-app-alist/assets/3351908/8dc2b2a6-140f-4c2e-adce-0d74974ea97d)

通过在 alist/Makefile添加如下代码即可编译成功
![image](https://github.com/sbwml/luci-app-alist/assets/3351908/aa43b20c-2afe-4ac5-8087-64abb20a0399)

好吧，其实我也不确定是不是alist这边修改就可以了，不过麻烦大佬看下了

**Comment by wzming** [comment]
补充一下环境 WSL2，openwrt master分支，alist master分支

**Comment by sbwml** [comment]
你这样做是对的

**Comment by wzming** [comment]
大佬抽空更新一下哈，麻烦了
