### ISSUE TITLE
3.20 R4SE 更新IPK后可以启动但无法访问

### ISSUE THREAD

**Issue by wcbspp** [sbwml/luci-app-alist#72]
回退3.19版本正常

**Comment by sbwml** [comment]
已修复

**Comment by GreenTeodoro839** [comment]
> 已修复

3.20和3.21编译都报错，换成3.19正常

**Comment by sbwml** [comment]
算命都要生辰八字，日志呢

**Comment by DHDAXCW** [comment]
``
d@d:~/actions/openwrt$ make package/alist/alist/compile V=99
make[2]: Entering directory '/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/scripts/config'
make[1]: Entering directory '/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt'
make[2]: Entering directory '/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/customfeeds/packages/lang/golang/golang'
make[2]: Leaving directory '/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/customfeeds/packages/lang/golang/golang'
time: package/feeds/packages/golang/host-compile#0.47#0.17#0.53
make[2]: Entering directory '/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/package/libs/toolchain'
echo "libc" >> /home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
echo "libgcc" >> /home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
echo "libatomic" >> /home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
echo "libstdcpp" >> /home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
echo "libpthread" >> /home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
echo "librt" >> /home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
make[2]: Leaving directory '/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/package/libs/toolchain'
time: package/libs/toolchain/compile#0.18#0.04#0.20
make[2]: Entering directory '/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/package/alist/alist'
rm -f /home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/build_dir/target-aarch64_generic_musl/alist-3.20.1/.built
touch /home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/build_dir/target-aarch64_generic_musl/alist-3.20.1/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/tmp/go-build" GO_MOD_CACHE_DIR="/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/alist-org/alist" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/alist-org/alist/..." GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/build_dir/target-aarch64_generic_musl/alist-3.20.1" GO_BUILD_DIR="/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/build_dir/target-aarch64_generic_musl/alist-3.20.1/.go_work/build" GO_BUILD_BIN_DIR="/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/build_dir/target-aarch64_generic_musl/alist-3.20.1/.go_work/build/bin/linux_arm64" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/staging_dir/target-aarch64_generic_musl/usr/share/gocode/src" GOOS="linux" GOARCH="arm64" GO386="" GOAMD64="" GOARM="" GOMIPS="" GOMIPS64="" GOPPC64="" CGO_ENABLED=1 CC="aarch64-openwrt-linux-musl-gcc" CXX="aarch64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/build_dir/target-aarch64_generic_musl/alist-3.20.1=alist-3.20.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -D_LARGEFILE64_SOURCE" CGO_CPPFLAGS="-I/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/usr/include -I/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/include/fortify -I/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/include" CGO_CXXFLAGS="-Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/build_dir/target-aarch64_generic_musl/alist-3.20.1=alist-3.20.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -D_LARGEFILE64_SOURCE" CGO_LDFLAGS="-L/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/usr/lib -L/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/lib -znow -zrelro" GOPATH="/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/build_dir/target-aarch64_generic_musl/alist-3.20.1/.go_work/build" GOCACHE="/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/tmp/go-build" GOMODCACHE="/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/dl/go-mod-cache" GOENV=off /usr/bin/env bash /home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/feeds/packages/lang/golang//golang-build.sh build -v -buildvcs=false -trimpath -ldflags "all=-buildid '1688104908' -linkmode external -extldflags '-L/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/usr/lib -L/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'"        -ldflags "-w -s -X github.com/alist-org/alist/v3/internal/conf.Version=v3.20.1-aarch64 -X github.com/alist-org/alist/v3/internal/conf.WebVersion=3.20.0 -buildid '1688104908' -linkmode external -extldflags '-L/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/usr/lib -L/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'"
Finding targets

Building targets
github.com/foxxorcat/mopan-sdk-go
# github.com/foxxorcat/mopan-sdk-go
../../../../../dl/go-mod-cache/github.com/foxxorcat/mopan-sdk-go@v0.1.0/client.go:145:26: undefined: errors.Join
note: module requires Go 1.20

make[2]: *** [Makefile:76: /home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/build_dir/target-aarch64_generic_musl/alist-3.20.1/.built] Error 2
make[2]: Leaving directory '/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/package/alist/alist'
time: package/alist/alist/compile#5.19#1.09#1.50
    ERROR: package/alist/alist failed to build.
make[1]: *** [package/Makefile:116: package/alist/alist/compile] Error 1
make[1]: Leaving directory '/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt'
make: *** [/home/d/actions/lbc/_work/LubanCat-LEDE/LubanCat-LEDE/openwrt/include/toplevel.mk:231: package/alist/alist/compile] Error 2
d@d:~/actions/openwrt$
``

**Comment by sbwml** [comment]
note: module requires Go 1.20

**Comment by DHDAXCW** [comment]
go 1.19升级到1.20就解决了 感谢大佬~
