### ISSUE TITLE
Comm: alist Not tainted 4.4.60 #0

### ISSUE THREAD

**Issue by mineoled** [sbwml/luci-app-alist#73]
1040.212434] pc : [<000000000040bf90>] lr : [<000000000040bf4c>] pstate: 20000000
[ 1040.215396] sp : 00000040002e93d0
[ 1040.222867] x29: 00000040002e93c8 x28: 00000040000021a0
[ 1040.231178] x27: 0000000000000000 x26: 0000000001efe658
[ 1040.236473] x25: 0000000000000036 x24: 0000000001ef8918
[ 1040.241769] x23: ffffffffffffffff x22: 0000000000000000
[ 1040.247115] x21: 00000000004749e4 x20: 00000040002e9598
[ 1040.252420] x19: 0000000000000000 x18: 0000000000000000
[ 1040.257653] x17: 00000040002e95b0 x16: 00000040002e23a0
[ 1040.262947] x15: 0000000000000008 x14: 0000000000000005
[ 1040.268242] x13: 000000000000002a x12: 000000000000019f
[ 1040.273540] x11: 0000000000000000 x10: 0000000000000000
[ 1040.278833] x9 : 00000040002239e0 x8 : 00000000000001b7
[ 1040.284129] x7 : 0000000000000001 x6 : 0000000000000000
[ 1040.289434] x5 : 0000000000000000 x4 : 0000000000000000
[ 1040.294718] x3 : 0000000000000200 x2 : 0000000000000001
[ 1040.300027] x1 : 00000040002239e0 x0 : ffffffffffffff9c
[ 1040.305308]
[ 1040.316034] alist[5524]: syscall 439
[ 1040.316058] Code: f94017e3 f9401be4 f9401fe5 d4000001 (b13ffc1f)
[ 1040.319086] CPU: 2 PID: 5524 Comm: alist Not tainted 4.4.60 #0
[ 1040.324814] Hardware name: ZN M2 (DT)
[ 1040.330620] task: ffffffc007364980 ti: ffffffc007364980 task.ti: ffffffc007364980
[ 1040.334265] PC is at 0x40bf90
[ 1040.341854] LR is at 0x40bf4c
[ 1040.344534] pc : [<000000000040bf90>] lr : [<000000000040bf4c>] pstate: 20000000
[ 1040.347521] sp : 00000040002e93d0
[ 1040.355136] x29: 00000040002e93c8 x28: 00000040000021a0
[ 1040.363473] x27: 0000000000000001 x26: 0000000001efe658
[ 1040.368596] x25: 0000000000000036 x24: 0000000000000000
[ 1040.373866] x23: 0000000000000000 x22: 0000000000000001
[ 1040.379161] x21: 0000000002eda500 x20: 0000007fc61c5600
[ 1040.384700] x19: 0000000000000000 x18: 0000000000000000
[ 1040.389792] x17: 00000040002e95b0 x16: 00000040002e23a0
[ 1040.395135] x15: 003b9aca00000000 x14: 0000000000000004
[ 1040.400361] x13: 000000000000002a x12: 0000000000000026
[ 1040.405635] x11: 0000000000000000 x10: 0000000000000000
[ 1040.410964] x9 : 00000040005fa250 x8 : 00000000000001b7
[ 1040.416235] x7 : 0000000000000001 x6 : 0000000000000000
[ 1040.421522] x5 : 0000000000000000 x4 : 0000000000000000
[ 1040.426817] x3 : 0000000000000200 x2 : 0000000000000001
[ 1040.432111] x1 : 00000040005fa250 x0 : ffffffffffffff9c
[ 1040.437405]
[ 1040.439413] alist[5524]: syscall 439
[ 1040.439434] Code: f94017e3 f9401be4 f9401fe5 d4000001 (b13ffc1f)
[ 1040.442717] CPU: 2 PID: 5524 Comm: alist Not tainted 4.4.60 #0
[ 1040.448702] Hardware name: ZN M2 (DT)
[ 1040.454468] task: ffffffc007364980 ti: ffffffc007364980 task.ti: ffffffc007364980
[ 1040.458178] PC is at 0x40bf90
[ 1040.465697] LR is at 0x40bf4c
[ 1040.468576] pc : [<000000000040bf90>] lr : [<000000000040bf4c>] pstate: 20000000
[ 1040.471548] sp : 00000040002e93d0
[ 1040.479053] x29: 00000040002e93c8 x28: 00000040000021a0
[ 1040.487320] x27: 0000000000000001 x26: 0000000001efe658
[ 1040.492615] x25: 0000000000000036 x24: 0000000000000000
[ 1040.497909] x23: 0000000000000000 x22: 0000000000000001
[ 1040.503263] x21: 0000000002eda500 x20: 00000040002e9658
[ 1040.508500] x19: 0000000000000000 x18: 0000000000000000
[ 1040.513795] x17: 00000040002e95b0 x16: 00000040002e23a0
[ 1040.519090] x15: 003b9aca00000000 x14: 0000000000000008
[ 1040.524385] x13: 000000000000002a x12: 0000000000000033
[ 1040.529758] x11: 0000000000000000 x10: 0000000000000000
[ 1040.534975] x9 : 00000040005fa320 x8 : 00000000000001b7
[ 1040.540384] x7 : 0000000000000001 x6 : 0000000000000000
[ 1040.545580] x5 : 0000000000000000 x4 : 0000000000000000
[ 1040.550870] x3 : 0000000000000200 x2 : 0000000000000001
[ 1040.556157] x1 : 00000040005fa320 x0 : ffffffffffffff9c
[ 1040.561451]
[ 1072.197798] alist[6840]: syscall 439
[ 1072.197821] Code: f94017e3 f9401be4 f9401fe5 d4000001 (b13ffc1f)
[ 1072.200623] CPU: 1 PID: 6840 Comm: alist Not tainted 4.4.60 #0
[ 1072.206502] Hardware name: ZN M2 (DT)
[ 1072.216710] task: ffffffc007365400 ti: ffffffc007365400 task.ti: ffffffc007365400
[ 1072.216743] PC is at 0x40bf90
[ 1072.223369] LR is at 0x40bf4c
[ 1072.226294] pc : [<000000000040bf90>] lr : [<000000000040bf4c>] pstate: 20000000
[ 1072.229337] sp : 00000040003293d0
[ 1072.236726] x29: 00000040003293c8 x28: 00000040000021a0
[ 1072.245037] x27: 0000000000000001 x26: 0000000001efe658
[ 1072.250402] x25: 0000000000000036 x24: 0000000001ef8918
[ 1072.255628] x23: ffffffffffffffff x22: 0000000000000008
[ 1072.260931] x21: 0000004000329468 x20: 0000004000329598
[ 1072.266218] x19: 0000007f639f0000 x18: 0000000000000000
[ 1072.271514] x17: 00000040003295b0 x16: 00000040003223a0
[ 1072.276809] x15: 0000000000000008 x14: 0000000000000005
[ 1072.282104] x13: 000000000000002a x12: 00000000000001bc
[ 1072.287451] x11: 0000000000000000 x10: 0000000000000000
[ 1072.293056] x9 : 00000040000ebbb0 x8 : 00000000000001b7
[ 1072.297991] x7 : 0000000000000001 x6 : 0000000000000000
[ 1072.303284] x5 : 0000000000000000 x4 : 0000000000000000
[ 1072.308588] x3 : 0000000000000200 x2 : 0000000000000001
[ 1072.313874] x1 : 00000040000ebbb0 x0 : ffffffffffffff9c
[ 1072.319169]
[ 1072.320866] alist[6840]: syscall 439
[ 1072.320916] Code: f94017e3 f9401be4 f9401fe5 d4000001 (b13ffc1f)
[ 1072.324479] CPU: 1 PID: 6840 Comm: alist Not tainted 4.4.60 #0
[ 1072.330490] Hardware name: ZN M2 (DT)
[ 1072.336427] task: ffffffc007365400 ti: ffffffc007365400 task.ti: ffffffc007365400
[ 1072.340052] PC is at 0x40bf90
[ 1072.347391] LR is at 0x40bf4c
[ 1072.352369] pc : [<000000000040bf90>] lr : [<000000000040bf4c>] pstate: 20000000
[ 1072.353299] sp : 00000040003293d0
[ 1072.360809] x29: 00000040003293c8 x28: 00000040000021a0
[ 1072.369276] x27: 0000000000000001 x26: 0000000001efe658
[ 1072.374385] x25: 0000000000000036 x24: 0000000000000000
[ 1072.379885] x23: 0000000000000000 x22: 0000000000000001
[ 1072.384969] x21: 0000000002eda500 x20: 0000004000329658
[ 1072.391912] x19: 0000000000000000 x18: 0000000000000000
[ 1072.396010] x17: 00000040003295b0 x16: 00000040003223a0
[ 1072.401310] x15: 003b9aca00000000 x14: 000000000000000c
[ 1072.406609] x13: 000000000000002a x12: 00000000000001c9
[ 1072.411896] x11: 0000000000000000 x10: 0000000000000000
[ 1072.417189] x9 : 00000040000ebc80 x8 : 00000000000001b7
[ 1072.422486] x7 : 0000000000000001 x6 : 0000000000000000
[ 1072.427779] x5 : 0000000000000000 x4 : 0000000000000000
[ 1072.433165] x3 : 0000000000000200 x2 : 0000000000000001
[ 1072.438370] x1 : 00000040000ebc80 x0 : ffffffffffffff9c
[ 1072.443665]
[ 1072.445557] alist[6840]: syscall 439
[ 1072.445582] Code: f94017e3 f9401be4 f9401fe5 d4000001 (b13ffc1f)
[ 1072.448976] CPU: 1 PID: 6840 Comm: alist Not tainted 4.4.60 #0
[ 1072.455050] Hardware name: ZN M2 (DT)
[ 1072.460826] task: ffffffc007365400 ti: ffffffc007365400 task.ti: ffffffc007365400
[ 1072.464427] PC is at 0x40bf90
[ 1072.472644] LR is at 0x40bf4c
[ 1072.474850] pc : [<000000000040bf90>] lr : [<000000000040bf4c>] pstate: 20000000
[ 1072.478082] sp : 00000040003293d0
[ 1072.485278] x29: 00000040003293c8 x28: 00000040000021a0
[ 1072.493578] x27: 0000000000000001 x26: 0000000001efe658
[ 1072.498909] x25: 0000000000000036 x24: 0000000000000000
[ 1072.504209] x23: 0000000000000000 x22: 0000000000000001
[ 1072.514383] x21: 0000000002eda500 x20: 0000004000329658
[ 1072.518479] x19: 0000000000000000 x18: 0000000000000000
[ 1072.523772] x17: 00000040003295b0 x16: 00000040003223a0
[ 1072.529091] x15: 003b9aca00000000 x14: 0000000000000010
[ 1072.534369] x13: 000000000000002a x12: 00000000000001d6
[ 1072.539719] x11: 0000000000000000 x10: 0000000000000000
[ 1072.544955] x9 : 00000040000ebd50 x8 : 00000000000001b7
[ 1072.551976] x7 : 0000000000000001 x6 : 0000000000000000
[ 1072.556073] x5 : 0000000000000000 x4 : 0000000000000000
[ 1072.561565] x3 : 0000000000000200 x2 : 0000000000000001
[ 1072.566852] x1 : 00000040000ebd50 x0 : ffffffffffffff9c
[ 1072.572070]
[ 1090.069339] alist[8217]: syscall 439
[ 1090.069364] Code: f94017e3 f9401be4 f9401fe5 d4000001 (b13ffc1f)
[ 1090.072175] CPU: 0 PID: 8217 Comm: alist Not tainted 4.4.60 #0
[ 1090.078186] Hardware name: ZN M2 (DT)
[ 1090.083880] task: ffffffc0070f3f00 ti: ffffffc0070f3f00 task.ti: ffffffc0070f3f00
[ 1090.088372] PC is at 0x40bf90
[ 1090.095034] LR is at 0x40bf4c
[ 1090.097869] pc : [<000000000040bf90>] lr : [<000000000040bf4c>] pstate: 20000000
[ 1090.101006] sp : 000000400053d3d0
[ 1090.108555] x29: 000000400053d3c8 x28: 00000040000021a0
[ 1090.116622] x27: 0000000000000000 x26: 0000000001efe658
[ 1090.122068] x25: 0000000000000036 x24: 0000000001ef8918
[ 1090.127218] x23: ffffffffffffffff x22: 0000000000000001
[ 1090.132479] x21: 0000000002eda500 x20: 000000400053d598
[ 1090.137767] x19: 0000000000000000 x18: 0000000000000000
[ 1090.143257] x17: 000000400053d5b0 x16: 00000040005363a0
[ 1090.148355] x15: 0000000000000008 x14: 0000000000000004
[ 1090.153710] x13: 000000000000002a x12: 0000000000000009
[ 1090.158945] x11: 0000000000000000 x10: 0000000000000000
[ 1090.164349] x9 : 000000400064e080 x8 : 00000000000001b7
[ 1090.169537] x7 : 0000000000000001 x6 : 0000000000000000
[ 1090.174839] x5 : 0000000000000000 x4 : 0000000000000000
[ 1090.180162] x3 : 0000000000000200 x2 : 0000000000000001
[ 1090.185423] x1 : 000000400064e080 x0 : ffffffffffffff9c
[ 1090.190727]
[ 1090.192406] alist[8217]: syscall 439
[ 1090.192459] Code: f94017e3 f9401be4 f9401fe5 d4000001 (b13ffc1f)
[ 1090.196071] CPU: 0 PID: 8217 Comm: alist Not tainted 4.4.60 #0
[ 1090.202149] Hardware name: ZN M2 (DT)
[ 1090.207860] task: ffffffc0070f3f00 ti: ffffffc0070f3f00 task.ti: ffffffc0070f3f00
[ 1090.211572] PC is at 0x40bf90
[ 1090.218947] LR is at 0x40bf4c
[ 1090.221959] pc : [<000000000040bf90>] lr : [<000000000040bf4c>] pstate: 20000000
[ 1090.224874] sp : 000000400053d3d0
[ 1090.232471] x29: 000000400053d3c8 x28: 00000040000021a0
[ 1090.240657] x27: 0000000000000000 x26: 0000000001efe658
[ 1090.245925] x25: 0000000000000036 x24: 0000000000000000
[ 1090.251254] x23: 0000000000000000 x22: 0000000000000001
[ 1090.256520] x21: 0000000002eda500 x20: 000000400053d658
[ 1090.261826] x19: 0000000000000000 x18: 0000000000000000
[ 1090.267107] x17: 000000400053d5b0 x16: 00000040005363a0
[ 1090.272411] x15: 003b9aca00000000 x14: 000000000000000b
[ 1090.277797] x13: 000000000000002a x12: 0000000000000016
[ 1090.282999] x11: 0000000000000000 x10: 0000000000000000
[ 1090.288287] x9 : 000000400064e150 x8 : 00000000000001b7
[ 1090.293593] x7 : 0000000000000001 x6 : 0000000000000000
[ 1090.298877] x5 : 0000000000000000 x4 : 0000000000000000
[ 1090.304189] x3 : 0000000000000200 x2 : 0000000000000001
[ 1090.309469] x1 : 000000400064e150 x0 : ffffffffffffff9c
[ 1090.314765]
[ 1090.316405] alist[8217]: syscall 439
[ 1090.316503] Code: f94017e3 f9401be4 f9401fe5 d4000001 (b13ffc1f)
[ 1090.320247] CPU: 0 PID: 8217 Comm: alist Not tainted 4.4.60 #0
[ 1090.326109] Hardware name: ZN M2 (DT)
[ 1090.331963] task: ffffffc0070f3f00 ti: ffffffc0070f3f00 task.ti: ffffffc0070f3f00
[ 1090.335534] PC is at 0x40bf90
[ 1090.343052] LR is at 0x40bf4c
[ 1090.345958] pc : [<000000000040bf90>] lr : [<000000000040bf4c>] pstate: 20000000
[ 1090.348899] sp : 000000400053d3d0
[ 1090.356617] x29: 000000400053d3c8 x28: 00000040000021a0
[ 1090.364679] x27: 0000000000000000 x26: 0000000001efe658
[ 1090.369995] x25: 0000000000000036 x24: 0000000000000000
[ 1090.375276] x23: 0000000000000000 x22: 0000000000000001
[ 1090.380682] x21: 0000000002eda500 x20: 000000400053d658
[ 1090.385862] x19: 0000000000000000 x18: 0000000000000000
[ 1090.391167] x17: 000000400053d5b0 x16: 00000040005363a0
[ 1090.396490] x15: 003b9aca00000000 x14: 000000000000000f
[ 1090.401753] x13: 000000000000002a x12: 0000000000000023
[ 1090.407040] x11: 0000000000000000 x10: 0000000000000000
[ 1090.412360] x9 : 000000400064e220 x8 : 00000000000001b7
[ 1090.417632] x7 : 0000000000000001 x6 : 0000000000000000
[ 1090.422922] x5 : 0000000000000000 x4 : 0000000000000000
[ 1090.428251] x3 : 0000000000000200 x2 : 0000000000000001
[ 1090.433526] x1 : 000000400064e220 x0 : ffffffffffffff9c
[ 1090.438808]
root@OpenWrt:~#

**Comment by mineoled** [comment]
机器是zn m2


主机名 | OpenWrt
-- | --
主机型号 | ZN M2
架构 | ARMv8 Processor rev 4 (v8l) x 4 (1056MHz, 58.0°C )
目标平台 | ipq60xx/generic
固件版本 | OpenWrt R23.5.1 / LuCI 1806 branch (git-23.123.19566-f90c5cd)
内核版本 | 4.4.60

**Comment by sbwml** [comment]
它是不是 OpenWrt 官方支持的设备？如果是可以做兼容支持。如果不是，你只能自己通过 SDK 去编译使用或给固件作者让编译固件时内置Alist。

再或者你可以试试到 alist 官方仓库下载二进制文的方式使用。

发自我的iPhone

**Comment by mineoled** [comment]
不是，那我试试自行构建吧
