### ISSUE TITLE
openwrt-22.03-mipsel_24kc安装alist后无法启动

### ISSUE THREAD

**Issue by boobb** [sbwml/luci-app-alist#75]
alist在点击启动后提示：未运行

相关解决方案：
https://github.com/istoreos/istoreos/issues/583

以上是目前遇到的两个bug，自从有这个以后路由器能够正常使用，感谢开发者的维护，祝好。

**Comment by boobb** [comment]
21.02可正常启动

**Comment by sbwml** [comment]
mipsel 设备在 openwrt 21、22 的运行库上有区别，https://github.com/sbwml/luci-app-alist/releases/tag/v3.24.0  在发布页面也能看到文件前缀 openwrt-21.02-xxxx.tar.gz  和  openwrt-22.03-xxxxx.tar.gz。你必须根据实际的openwrt 版本下载对应的 ipk 压缩包进行安装，才能正常使用。

如果你使用的是被魔改过的 openwrt ，不知道 musl 运行库版本，你可以直接使用 README 页面的安装脚本进行安装，它会自动识别你当前系统的 musl 并下载对应架构的alist 进行安装

**Comment by boobb** [comment]
冒昧求教，如何使用README页面的安装脚本进行安装？有该项目的地址或者是教程嘛？
才刚刚开始玩，给您添麻烦了真的不好意思。

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-alist#how-to-install-prebuilt-packages

**Comment by boobb** [comment]
上周有事，一下子忘了抱歉，感谢回复

**Comment by bamboocc** [comment]
> mipsel 设备在 openwrt 21、22 的运行库上有区别，https://github.com/sbwml/luci-app-alist/releases/tag/v3.24.0 在发布页面也能看到文件前缀 openwrt-21.02-xxxx.tar.gz 和 openwrt-22.03-xxxxx.tar.gz。你必须根据实际的openwrt 版本下载对应的 ipk 压缩包进行安装，才能正常使用。
> 
> 如果你使用的是被魔改过的 openwrt ，不知道 musl 运行库版本，你可以直接使用 README 页面的安装脚本进行安装，它会自动识别你当前系统的 musl 并下载对应架构的alist 进行安装

你好，我在按照readme后出现了以下的内容

我的设备是小米CR6608，MediaTek MT7621 ver:1 eco:3 x 4

root@BleachWrt:~# opkg update
Downloading https://mirrors.tencent.com/lede/releases/24.10.0-rc1/targets/ramips/mt7621/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://mirrors.tencent.com/lede/releases/24.10.0-rc1/packages/mipsel_24kc/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://mirrors.tencent.com/lede/releases/24.10.0-rc1/packages/mipsel_24kc/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://mirrors.tencent.com/lede/releases/24.10.0-rc1/packages/mipsel_24kc/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://mirrors.tencent.com/lede/releases/24.10.0-rc1/packages/mipsel_24kc/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://mirrors.tencent.com/lede/releases/24.10.0-rc1/packages/mipsel_24kc/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
root@BleachWrt:~# opkg install curl

Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Upgrading curl on root from 8.6.0-1 to 8.10.1-r1...
Downloading https://mirrors.tencent.com/lede/releases/24.10.0-rc1/packages/mipsel_24kc/packages/curl_8.10.1-r1_mipsel_24kc.ipk
Configuring curl.
root@BleachWrt:~#
root@BleachWrt:~# sh -c "$(curl -ksS https://raw.githubusercontent.com/sbwml/luc
i-app-alist/main/install.sh)"
Error loading shared library libmbedtls.so.21: No such file or directory (needed by /usr/bin/curl)
Error loading shared library libmbedx509.so.7: No such file or directory (needed by /usr/bin/curl)
Error loading shared library libmbedcrypto.so.16: No such file or directory (needed by /usr/bin/curl)
root@BleachWrt:~#
root@BleachWrt:~# ^C

root@BleachWrt:~#

**Comment by sbwml** [comment]
你的固件存在abi问题，建议找固件作者。

发自我的iPhone
