### ISSUE TITLE
一键安装脚本好像没有用

### ISSUE THREAD

**Issue by a447948814** [sbwml/luci-app-alist#76]
我在终端里直接粘贴进去回车没反应，是我用的不对吗？
![QQ截图20230809154329](https://github.com/sbwml/luci-app-alist/assets/61766946/17685af1-ab69-45ac-9f2e-f8bc9c0c7fbf)

**Comment by a447948814** [comment]
![image](https://github.com/sbwml/luci-app-alist/assets/61766946/a7e8416b-dd58-4907-8363-0140aee852f9)
网络看着没问题 可以打开脚本

**Comment by sbwml** [comment]
网络有没有问题，终端得真相

`curl -I -4 -m 3 -t 3 -o /dev/null -s -w %{http_code} http://www.google.com/generate_204`

如果返回 `204` ，你的网络才真整没有问题。无返回或返回数字不是 204，那就好好调整你的网络

**Comment by a447948814** [comment]
> 网络有没有问题,终端得真相
> 
> `curl -I -4 -m 3 -t 3 -o /dev/null -s -w %{http_code} http://www.google.com/generate_204`
> 
> 如果返回`204`,你的网络才真整没有问题。无返回或返回数字不是 204,那就好好调整你的网络

难道这个地址被墙了？确实没有返回、因为路由器我没配置墙外网络。刚脚本截图我是有墙外网络的情况下访问的。

> ps: ![image](https://user-images.githubusercontent.com/16485166/259340703-01bb4b4e-5645-4ca1-a642-c494391ea406.png)你这个东西,他不是有商店的吗,你直接在人家的商店安装就没有网络问题了

对  我是在商店安装的 但是版本太老了，，作者不更新，让我自己pr我也不会，所以找到你这里了。感谢。如果脚本没问题那就是我的本地问题了，我先手动安装了。
