### ISSUE TITLE
读取密码错误

### ISSUE THREAD

**Issue by mimokini** [sbwml/luci-app-alist#77]
使用的版本：v3.25.1
型号：openwrt-21.02-aarch64_cortex-a53.tar.gz
原因：读取的密码返回值成了时间
以下是原信息：
***********************************************
查看密码	 用户名：07:29:03]密码：07:29:03]
***********************************************
应该是读取的返回值错行了，请修正一下

**Comment by sbwml** [comment]
没得修正，这个东西已经不存在

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-alist/releases/tag/v3.25.1

可以试试 https://github.com/sbwml/luci-app-alist/commit/ff70952432ec302157e74d05f85e74f6de662f3e ，alist 现在只有重置密码，没有查看密码
