### ISSUE TITLE
使用夸克观看视频被限速

### ISSUE THREAD

**Issue by boobb** [sbwml/luci-app-alist#81]
这个问题似乎官方有提过:
https://github.com/alist-org/alist/issues/4318
然后似乎是在这里修复的:
https://github.com/alist-org/alist/issues/5217?ssp=1&darkschemeovr=1&setlang=zh-HK&safesearch=moderate
辛苦大佬研究一下，感谢！

**Comment by sbwml** [comment]
在这里讨论这种话题是毫无意义的，因为这里只是 OpenWrt 平台的一个守护进程，它不是一个分支维护。

**Comment by boobb** [comment]
> 讨论这个话题是没有意义的，因为这里只是 OpenWrt 平台的一个监视进程，它不是一个分支维护。

不好意思，打扰了
