### ISSUE TITLE
ImmortalWrt 21.02.7 X86_64 不能正常使用

### ISSUE THREAD

**Issue by SunHHB** [sbwml/luci-app-alist#82]
3.28 安装不报错，但是无法使用。luci 比官方的Package版本低，手动安装后，无法正常使用。

**Comment by sbwml** [comment]
先尝试命令能不能启动

```sh
/usr/bin/alist server --data /etc/alist
```

**Comment by SunHHB** [comment]
谢谢，已经解决了。是新旧版本冲突的问题。

**Comment by SunHHB** [comment]
> 先尝试命令能不能启动
> 
> ```shell
> /usr/bin/alist server --data /etc/alist
> ```

建议更新下luci的版本，方便直接固件打包，谢谢！

**Comment by sbwml** [comment]
我没懂你的意思，releases 提供的 ipk 基于 openwrt21.02、22.03 编译，随便拿一个他都能跑在当前 openwrt 所有 luci 上。

**Comment by sbwml** [comment]
即使是lede ，理论上也同样能跑，因为 21.02/22.03 没有依赖的添加，只有23.05 sdk 会多一个依赖 `luci-lua-runtime`，但当前的 sdk 编译出来 23.05 的luci 同样能跑

**Comment by SunHHB** [comment]
> 即使是lede ，理论上也同样能跑，因为 21.02/22.03 没有依赖的添加，只有23.05 sdk 会多一个依赖 `luci-lua-runtime`，但当前的 sdk 编译出来 23.05 的luci 同样能跑

您的意思是22.03的可以跑到21.02上面，是吗？因为openwrt的luci比ImmortalWrt 版本低。

**Comment by SunHHB** [comment]
您编译的版本                 官方源版本
luci-app-alist | 1.0.11 » git-23.228.33161-d69f83d

luci-i18n-alist-zh-cn | git-23.223.34172-ff70952 » git-23.228.33161-d69f83d

直接[ImageBuilder总是安装官方的源包，我fork改版本号 编译下ipk

**Comment by sbwml** [comment]
我明白你的意思了。你这种情况不需要使用这里的版本了。ImmortalWrt 现在有自己的 alist 和 luci，直接使用它自带的就可以了
