### ISSUE TITLE
配置ssl证书后无法启动

### ISSUE THREAD

**Issue by laorentou666** [sbwml/luci-app-alist#84]
## 复现流程
我想为我的网盘上https（端口映射至公网），但在ssl处填写证书路径并保存后luci内变成了“未运行”，无法进入后台
于是我尝试使用acme生成证书并重复之前的操作，没有问题，可以进入后台，但过几天后又变成之前的情况

![QQ图片20231104160614](https://github.com/sbwml/luci-app-alist/assets/89732460/4141ebfb-626b-428f-8f62-fff95f7c09aa)

![image](https://github.com/sbwml/luci-app-alist/assets/89732460/285058e5-f160-4e4a-88fa-e82f516e5eb3)

尝试在ssh执行alist start，提示如图
![image](https://github.com/sbwml/luci-app-alist/assets/89732460/561154e7-a3e8-4b20-a64f-675d1bd9580a)

执行service alist start，提示如图，我尝试修改文件权限但无效
![image](https://github.com/sbwml/luci-app-alist/assets/89732460/d8368423-6375-4b1e-a588-2e548121d754)

尝试opkg remove&install依旧提示未运行
## 期望
能够运行

**Comment by sbwml** [comment]
你的文件系统只读了，alist 配置文件生成不出来

**Comment by laorentou666** [comment]
> 你的文件系统只读了，alist 配置文件生成不出来

我该如何解决？这是我的diskman信息
但我没有修改过文件系统，仅仅加了一个ssl而已，怎么会莫名其妙无法启动呢
![image](https://github.com/sbwml/luci-app-alist/assets/89732460/3dc2f8f3-8362-40dc-aa81-8f6df7812561)

**Comment by sbwml** [comment]
文件系统只读跟你操作了什么东西无关，尽量避免使用ext4 文件系统基本能避免这种问题

**Comment by laorentou666** [comment]
> 文件系统只读跟你操作了什么东西无关，尽量避免使用ext4 文件系统基本能避免这种问题

好的，感谢！
