### ISSUE TITLE
更新后alist的logo不显示了

### ISSUE THREAD

**Issue by zcy85611** [sbwml/luci-app-alist#88]
openwrt官方最新的源码，使用的alist 3.29.1，发现进入alist后，左上角的logo没有了，一直在转圈圈，应该是找不到logo文件的原因。

进入alist后，在logo处，显示的logo路径是/assets/logo.svg

是否alist在源码上做了什么更改导致不显示logo?

**Comment by sbwml** [comment]
未复现

![image](https://github.com/sbwml/luci-app-alist/assets/16485166/a14960ad-54ec-4deb-9f6e-c992ca43b700)

**Comment by zcy85611** [comment]
> 未复现
> 
> ![image](https://private-user-images.githubusercontent.com/16485166/292873635-a14960ad-54ec-4deb-9f6e-c992ca43b700.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NDE4NTUsIm5iZiI6MTcwMzY0MTU1NSwicGF0aCI6Ii8xNjQ4NTE2Ni8yOTI4NzM2MzUtYTE0OTYwYWQtNTRlYy00ZGViLTlmNmUtYzk5MmNhNDNiNzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDAxNDU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYjgyMmZhZjhjNWRlMTUxNDU4ZjExY2IzOGQ4OGNiODZkY2RlM2Q1NDdlZDE5MzJhZTY0NjFlYjZiZGUwNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cNdQBUDmi_5BafoJsUntZWwDSF5fqiwi-NEQqfp8eTU)

感谢回复，我按照你的方式再测试一下，晚点来反馈

**Comment by zcy85611** [comment]
![屏幕截图 2023-12-27 231118](https://github.com/sbwml/luci-app-alist/assets/23516464/b8e6a92a-c011-45d5-982b-838474f96543)
我的是这样的，这么看也没有什么问题，但是logo就是不显示

**Comment by sbwml** [comment]
无痕模式试试？

**Comment by sbwml** [comment]
你应该点下面那一个看看
![image](https://github.com/sbwml/luci-app-alist/assets/16485166/a0c9c332-7deb-4333-a7c8-82ce76819b4c)

**Comment by sbwml** [comment]
或者你直接把 logo 地址 `/assets/logo.svg` 设置成官方默认地址 `https://cdn.jsdelivr.net/gh/alist-org/logo@main/logo.svg`

**Comment by zcy85611** [comment]
![屏幕截图 2023-12-29 093444](https://github.com/sbwml/luci-app-alist/assets/23516464/d153eb05-3c8e-49b5-b183-6b14ac8a14d9)
也看了下这个，好像也没看出什么问题了，虽然不是很重要的问题，但就是觉得有点奇怪
