### ISSUE TITLE
github.cooluc.com镜像坏了

### ISSUE THREAD

**Issue by ZYong9908** [sbwml/luci-app-alist#89]
![image](https://github.com/sbwml/luci-app-alist/assets/44081531/aa32348c-7160-4479-8511-3ef4f458096a)

**Comment by sbwml** [comment]
被人滥用  服务器被整的gfw了

**Comment by sbwml** [comment]
现在这个域名取消解析了   玩些时候   移除镜像地址    能不能安装    怎么安装   靠个人了

**Comment by ZYong9908** [comment]
刚手动下载把脚本改成解压本地包更新成功了，不过我傻了，忘记仔细看看代码了，现在目录被删了

Bard ***@***.***> 于 2024年1月6日周六 12:05写道：
