### ISSUE TITLE
装完alist，服务菜单变成网络存储了

### ISSUE THREAD

**Issue by youngking525** [sbwml/luci-app-alist#90]
请教一下大佬，我用的op固件没有网络存储这个菜单项，装完alist之后，原来的服务变成网络存储了，之前在服务菜单里的插件也都在这个网络存储菜单里了，这个要怎么改啊

**Comment by sbwml** [comment]
`luci-app-alist` 不会把 `服务` 菜单变成其它，它只会创建一个 `网络存储` 菜单，该菜单如果不存在则创建

**Comment by youngking525** [comment]
谢谢大佬解惑，之前在别的地方下的luci包的锅，卸了拿你这里的重新安装就好了
