### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by caixin1218** [sbwml/luci-app-alist#93]
可能是依赖有问题，在Ubuntu 22 LTS 系统上没有问题，但在国产 deepin 深度系统上有问题。

make[3]: Entering directory '/home/caixin/router/6.1.32/package/boot/grub2'
mkdir -p /home/caixin/router/6.1.32/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/caixin/router/6.1.32/tmp/.root-copy.flock -c 'cp -fpR /home/caixin/router/6.1.32/build_dir/target-x86_64_musl/linux-x86_64/grub-pc/grub-2.06/.pkgdir/grub2/. /home/caixin/router/6.1.32/staging_dir/target-x86_64_musl/root-x86/'
touch /home/caixin/router/6.1.32/staging_dir/target-x86_64_musl/root-x86/stamp/.grub2_installed
echo "grub2" >> /home/caixin/router/6.1.32/staging_dir/target-x86_64_musl/pkginfo/grub2.pc.install
make[3]: Leaving directory '/home/caixin/router/6.1.32/package/boot/grub2'
time: package/boot/grub2/pc/compile#1.80#0.10#0.40
make[3]: Entering directory '/home/caixin/router/6.1.32/feeds/packages/lang/golang/golang'
make[3]: Leaving directory '/home/caixin/router/6.1.32/feeds/packages/lang/golang/golang'
time: package/feeds/packages/golang/host-compile#4.26#0.93#0.68
make[3]: Entering directory '/home/caixin/router/6.1.32/package/system/ca-certificates'
mkdir -p /home/caixin/router/6.1.32/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/caixin/router/6.1.32/tmp/.root-copy.flock -c 'cp -fpR /home/caixin/router/6.1.32/build_dir/target-x86_64_musl/ca-certificates-20211016/.pkgdir/ca-bundle/. /home/caixin/router/6.1.32/staging_dir/target-x86_64_musl/root-x86/'
touch /home/caixin/router/6.1.32/staging_dir/target-x86_64_musl/root-x86/stamp/.ca-bundle_installed
echo "ca-bundle" >> /home/caixin/router/6.1.32/staging_dir/target-x86_64_musl/pkginfo/ca-certificates.default.install
mkdir -p /home/caixin/router/6.1.32/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/caixin/router/6.1.32/tmp/.root-copy.flock -c 'cp -fpR /home/caixin/router/6.1.32/build_dir/target-x86_64_musl/ca-certificates-20211016/.pkgdir/ca-certificates/. /home/caixin/router/6.1.32/staging_dir/target-x86_64_musl/root-x86/'
touch /home/caixin/router/6.1.32/staging_dir/target-x86_64_musl/root-x86/stamp/.ca-certificates_installed
echo "ca-certificates" >> /home/caixin/router/6.1.32/staging_dir/target-x86_64_musl/pkginfo/ca-certificates.default.install
make[3]: Leaving directory '/home/caixin/router/6.1.32/package/system/ca-certificates'
time: package/system/ca-certificates/compile#0.17#0.06#0.22
make[3]: Entering directory '/home/caixin/router/6.1.32/feeds/Alist/alist'
rm -f /home/caixin/router/6.1.32/build_dir/target-x86_64_musl/alist-3.30.0/.built
touch /home/caixin/router/6.1.32/build_dir/target-x86_64_musl/alist-3.30.0/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/caixin/router/6.1.32/tmp/go-build" GO_MOD_CACHE_DIR="/home/caixin/router/6.1.32/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/alist-org/alist" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/alist-org/alist/..." GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/caixin/router/6.1.32/build_dir/target-x86_64_musl/alist-3.30.0" GO_BUILD_DIR="/home/caixin/router/6.1.32/build_dir/target-x86_64_musl/alist-3.30.0/.go_work/build" GO_BUILD_BIN_DIR="/home/caixin/router/6.1.32/build_dir/target-x86_64_musl/alist-3.30.0/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/caixin/router/6.1.32/staging_dir/target-x86_64_musl/usr/share/gocode/src" GOOS="linux" GOARCH="amd64" GO386="" GOAMD64="v1" GOARM="" GOMIPS="" GOMIPS64="" GOPPC64="" CGO_ENABLED=1 CC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/caixin/router/6.1.32/build_dir/target-x86_64_musl/alist-3.30.0=alist-3.30.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -D_LARGEFILE64_SOURCE" CGO_CPPFLAGS="-I/home/caixin/router/6.1.32/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/home/caixin/router/6.1.32/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/home/caixin/router/6.1.32/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include" CGO_CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/caixin/router/6.1.32/build_dir/target-x86_64_musl/alist-3.30.0=alist-3.30.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -D_LARGEFILE64_SOURCE" CGO_LDFLAGS="-L/home/caixin/router/6.1.32/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/caixin/router/6.1.32/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro" GOPATH="/home/caixin/router/6.1.32/build_dir/target-x86_64_musl/alist-3.30.0/.go_work/build" GOCACHE="/home/caixin/router/6.1.32/tmp/go-build" GOMODCACHE="/home/caixin/router/6.1.32/dl/go-mod-cache" GOENV=off GOTOOLCHAIN=local /usr/bin/env bash /home/caixin/router/6.1.32/feeds/packages/lang/golang//golang-build.sh build -v -buildvcs=false -trimpath -ldflags "all=-buildid '1686251287' -linkmode external -extldflags '-L/home/caixin/router/6.1.32/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/caixin/router/6.1.32/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'" -ldflags "-w -s -X github.com/alist-org/alist/v3/internal/conf.Version=v3.30.0-x86_64 -X github.com/alist-org/alist/v3/internal/conf.WebVersion=3.30.0 -buildid '1686251287' -linkmode external -extldflags '-L/home/caixin/router/6.1.32/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/caixin/router/6.1.32/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'"
Finding targets

Building targets
github.com/winfsp/cgofuse/fuse

github.com/winfsp/cgofuse/fuse
../../../../../dl/go-mod-cache/github.com/winfsp/cgofuse@v1.5.1-0.20230130140708-f87f5db493b5/fuse/host_cgo.go:117:10: fatal error: fuse.h: No such file or directory
117 | #include <fuse.h>
| ^~~~~~~~
compilation terminated.

make[3]: *** [Makefile:76: /home/caixin/router/6.1.32/build_dir/target-x86_64_musl/alist-3.30.0/.built] Error 1
make[3]: Leaving directory '/home/caixin/router/6.1.32/feeds/Alist/alist'
time: package/feeds/Alist/alist/compile#89.15#42.95#3.30
ERROR: package/feeds/Alist/alist failed to build.
make[2]: *** [package/Makefile:116: package/feeds/Alist/alist/compile] Error 1
make[2]: Leaving directory '/home/caixin/router/6.1.32'
make[1]: *** [package/Makefile:110: /home/caixin/router/6.1.32/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/caixin/router/6.1.32'
make: *** [/home/caixin/router/6.1.32/include/toplevel.mk:231：world] 错误 2

**Comment by sbwml** [comment]
看 readme

发自我的iPhone

**Comment by caixin1218** [comment]
> 看 readme 发自我的iPhone
> […](#)


真奇怪，我现在单独安装就可以了。 但是我之前已经安装过的。是复制安装的，像这样的，会漏掉？？
sudo apt update -y
sudo apt full-upgrade -y
sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev \
libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev \
libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 \
python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo \
uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

**Comment by sbwml** [comment]
主要是  libfuse-dev 开发包

发自我的iPhone

> 在 2024年1月16日，18:11，cai ***@***.***> 写道：
> 
> libfuse-dev

**Comment by caixin1218** [comment]
> 主要是 libfuse-dev 开发包 发自我的iPhone
> […](#)
> 在 2024年1月16日，18:11，cai ***@***.***> 写道： libfuse-dev

ok  已经解决了
