### ISSUE TITLE
v3.31.0没发布openwrt-21.02-xxx版本

### ISSUE THREAD

**Issue by Narut0123** [sbwml/luci-app-alist#98]
以前都会同时发布openwrt-21.02-xxx和openwrt-22.03-xxx各版本，怎么这次只发布openwrt-22.03-xxx版本了啊？

**Comment by sbwml** [comment]
21.02 全部出错了     晚点再看看是什么情况

发自我的iPhone

**Comment by Narut0123** [comment]
> 21.02 全部出错了 晚点再看看是什么情况 发自我的iPhone
> […](#)
> 在 2024年2月24日，08:39，Narut0123 ***@***.***> 写道： ﻿ 以前都会同时发布openwrt-21.02-xxx和openwrt-22.03-xxx各版本，怎么这次只发布openwrt-22.03-xxx版本了啊？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

原来如此，大佬您辛苦了

**Comment by sbwml** [comment]
现在有了

发自我的iPhone

**Comment by Narut0123** [comment]
> 现在有了 发自我的iPhone
> […](#)
> 在 2024年2月24日，09:39，Narut0123 ***@***.***> 写道： ﻿ 21.02 全部出错了 晚点再看看是什么情况 发自我的iPhone … 在 2024年2月24日，08:39，Narut0123 @.***> 写道： ﻿ 以前都会同时发布openwrt-21.02-xxx和openwrt-22.03-xxx各版本，怎么这次只发布openwrt-22.03-xxx版本了啊？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread. 原来如此，大佬您辛苦了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

感谢大佬！这就下载
