### ISSUE TITLE
大佬MTK7981这一芯片是armv8架构请问用哪个啊

### ISSUE THREAD

**Issue by RainTsal** [sbwml/luci-app-alist#99]
找了好久也试了四五个，比如arm的a8这些都试过了不行
<img width="676" alt="屏幕截图 2024-03-03 152002" src="https://github.com/sbwml/luci-app-alist/assets/78639461/f058775d-91ff-437c-96c9-8dd75bd7e596">

**Comment by sbwml** [comment]
朋友你找错地方了，你这跟包并不来自这里

**Comment by sbwml** [comment]
通常这两个命令都可以查看包架构信息：

1、`. /etc/openwrt_release && echo $DISTRIB_ARCH`

2、`opkg print-architecture`

**Comment by FreeAlieX** [comment]
> 通常这两个命令都可以查看包的架构信息：
> 
> 1、`. /etc/openwrt_release && echo $DISTRIB_ARCH`
> 
> 2、`opkg print-architecture`

您好用了您这个代码后，提示：root@ImmortalWrt:~# . /etc/openwrt_release && echo $DISTRIB_ARCH
mipsel_24kc
root@ImmortalWrt:~# opkg print-architecture
arch all 1
arch noarch 1
arch mipsel_24kc 10

应该用openwrt-22.03-mipsel_24kc还是openwrt-21.02-mipsel_24kc比较合适，请教一下
